"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, CircleAlert, Dices, LogOut, Minus, Plus, RefreshCcw, Shield, Sparkles } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { migrateLegacyData } from "../legacy-migration";
import { auditCharacter } from "../character-audit";
import { InconsistencySheet } from "../inconsistency-sheet";
import { DEFAULT_CHRONICLE_RULES, type ChronicleRules } from "../game-rules";
import { xpBudget, xpSpent, type XpPurchase } from "../experience";

type Values=Record<string,number>;
type Specialty={skill:string;name:string;source:string};
type Merit={name:string;dots:number;source:string;notes:string};
type RolledDie={value:number;hunger:boolean};
type RollRecord={id:string;kind:"test"|"rouse";label:string;pool:number;hunger:number;difficulty:number;dice:RolledDie[];successes:number;outcome:string;createdAt:string;margin?:number;rerolled?:boolean};
type GameData={
  attributes:Values;skills:Values;disciplines:Values;disciplinePowers:Record<string,string[]>;specialties:Specialty[];merits:Merit[];flawItems:Merit[];
  predator:string;humanity:number;hunger:number;stains:number;healthSuperficial:number;healthAggravated:number;willpowerSuperficial:number;willpowerAggravated:number;
  convictions:string;touchstones:string;ambition:string;desire:string;clanBane:string;clanCompulsion:string;resonance:string;bloodPotency:number;generation:string;
  xpTotal:string;xpSpent:string;xpPurchases:XpPurchase[];chronicle:string;notes:string;ageCategory?:string;skillPreset?:string;predatorApplied?:string;predatorDiscipline?:string;predatorResolutions?:Record<string,string>;chronicleRules:ChronicleRules;allowHomebrew?:boolean;rollHistory?:RollRecord[];[key:string]:unknown;
};
type Character={id:number;name:string;concept:string;clan:string;sourcebook:string;data:GameData};
const defaults:GameData={attributes:{},skills:{},disciplines:{},disciplinePowers:{},specialties:[],merits:[],flawItems:[],predator:"",humanity:7,hunger:1,stains:0,healthSuperficial:0,healthAggravated:0,willpowerSuperficial:0,willpowerAggravated:0,convictions:"",touchstones:"",ambition:"",desire:"",clanBane:"",clanCompulsion:"",resonance:"",bloodPotency:1,generation:"13ª",xpTotal:"",xpSpent:"",xpPurchases:[],chronicle:"",notes:"",chronicleRules:{...DEFAULT_CHRONICLE_RULES}};
const normalize=(value:Character):Character=>({...value,data:migrateLegacyData({...defaults,...(value.data||{}),attributes:value.data?.attributes||{},skills:value.data?.skills||{},disciplines:value.data?.disciplines||{},disciplinePowers:value.data?.disciplinePowers||{},specialties:value.data?.specialties||[],merits:value.data?.merits||[],flawItems:value.data?.flawItems||[],xpPurchases:value.data?.xpPurchases||[],predatorResolutions:value.data?.predatorResolutions||{},chronicleRules:{...DEFAULT_CHRONICLE_RULES,...(value.data?.chronicleRules||{})}}).data as GameData});

function evaluateTest(dice:RolledDie[],difficulty:number){const base=dice.filter(die=>die.value>=6).length,tens=dice.filter(die=>die.value===10).length,successes=base+2*Math.floor(tens/2),passed=successes>=difficulty,critical=tens>=2,messy=passed&&critical&&dice.some(die=>die.hunger&&die.value===10),bestial=!passed&&dice.some(die=>die.hunger&&die.value===1);return{successes,margin:successes-difficulty,outcome:messy?"Crítico bagunçado":passed&&critical?"Sucesso crítico":passed?"Sucesso":bestial?"Falha bestial":"Falha"}}

export default function GameSheet({displayName,signOutPath}:{displayName:string;signOutPath:string}){
  const [characters,setCharacters]=useState<Character[]>([]),[character,setCharacter]=useState<Character|null>(null),[status,setStatus]=useState<"loading"|"saved"|"saving"|"error">("loading"),[auditOpen,setAuditOpen]=useState(false),[rollPool,setRollPool]=useState(5),[rollDifficulty,setRollDifficulty]=useState(3),[rollLabel,setRollLabel]=useState(""),[rollTraitA,setRollTraitA]=useState(""),[rollTraitB,setRollTraitB]=useState(""),[rollModifier,setRollModifier]=useState(0),[useSpecialty,setUseSpecialty]=useState(false);
  const persisted=useRef("");
  useEffect(()=>{fetch("/api/characters").then(async response=>{if(!response.ok)throw new Error();return await response.json() as {characters:Character[]}}).then(({characters})=>{const safe=characters.map(normalize);setCharacters(safe);const requested=Number(new URLSearchParams(window.location.search).get("id"));const initial=safe.find(item=>item.id===requested)??safe[0]??null;setCharacter(initial);persisted.current=JSON.stringify(initial);setStatus("saved")}).catch(()=>setStatus("error"))},[]);
  useEffect(()=>{if(!character||status==="loading"||JSON.stringify(character)===persisted.current)return;const timer=setTimeout(async()=>{setStatus("saving");try{const response=await fetch(`/api/characters/${character.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(character)});if(!response.ok)throw new Error();const {character:saved}=await response.json() as {character:Character};const safe=normalize(saved);persisted.current=JSON.stringify(safe);setCharacter(safe);setCharacters(items=>items.map(item=>item.id===safe.id?safe:item));setStatus("saved")}catch{setStatus("error")}},600);return()=>clearTimeout(timer)},[character,status]);
  const setData=<K extends keyof GameData>(key:K,value:GameData[K])=>setCharacter(current=>current?{...current,data:{...current.data,[key]:value}}:current);
  const selectCharacter=(id:number)=>{const next=characters.find(item=>item.id===id)??null;setCharacter(next);persisted.current=JSON.stringify(next);history.replaceState(null,"",`/play?id=${id}`)};
  const healthMax=(character?.data.attributes.Vigor||1)+3,willpowerMax=(character?.data.attributes.Autocontrole||1)+(character?.data.attributes.Determinação||1);
  const specialtiesBySkill=useMemo(()=>Object.groupBy(character?.data.specialties||[],item=>item.skill),[character]);
  const auditIssues=useMemo(()=>character?auditCharacter({name:character.name,concept:character.concept,clan:character.clan,data:character.data}):[],[character]);
  const traitOptions=useMemo(()=>{if(!character)return[];return[
    ...Object.entries(character.data.attributes).filter(([,value])=>value>0).map(([name,value])=>({key:`attribute:${name}`,name,value,group:"Atributos"})),
    ...Object.entries(character.data.skills).filter(([,value])=>value>0).map(([name,value])=>({key:`skill:${name}`,name,value,group:"Habilidades"})),
    ...Object.entries(character.data.disciplines).filter(([,value])=>value>0).map(([name,value])=>({key:`discipline:${name}`,name,value,group:"Disciplinas"})),
  ]},[character]);
  if(status==="loading")return <main className="play-loading">Abrindo ficha…</main>;
  if(!character)return <main className="play-empty"><Shield size={38}/><h1>Nenhuma ficha disponível</h1><p>Crie um personagem antes de abrir o modo de jogo.</p><Link href="/">Criar personagem</Link></main>;
  const selectedTraits=[traitOptions.find(item=>item.key===rollTraitA),traitOptions.find(item=>item.key===rollTraitB)].filter(Boolean) as typeof traitOptions;
  const selectedSpecialties=selectedTraits.flatMap(item=>item.group==="Habilidades"?(specialtiesBySkill[item.name]||[]):[]);
  const builtPool=selectedTraits.length?Math.max(1,Math.min(30,selectedTraits.reduce((total,item)=>total+item.value,0)+rollModifier+(useSpecialty&&selectedSpecialties.length?1:0))):Math.max(1,Math.min(30,rollPool));
  const defaultRollLabel=selectedTraits.map(item=>item.name).join(" + ");
  const recordRoll=(record:RollRecord)=>setData("rollHistory",[record,...(character.data.rollHistory||[])].slice(0,20));
  const rollTest=()=>{const pool=builtPool,hunger=Math.min(pool,Math.max(0,character.data.hunger)),difficulty=Math.max(1,Math.min(10,rollDifficulty)),dice:Array<RolledDie>=Array.from({length:pool},(_,index)=>({value:Math.floor(Math.random()*10)+1,hunger:index<hunger})),result=evaluateTest(dice,difficulty);recordRoll({id:crypto.randomUUID(),kind:"test",label:rollLabel.trim()||defaultRollLabel||"Teste",pool,hunger,difficulty,dice,...result,createdAt:new Date().toISOString()})};
  const rerollWillpower=(record:RollRecord)=>{if(record.kind!=="test"||record.rerolled||character.data.willpowerSuperficial+character.data.willpowerAggravated>=willpowerMax)return;let remaining=3;const dice=record.dice.map(die=>{if(remaining>0&&!die.hunger&&die.value<6){remaining-=1;return{...die,value:Math.floor(Math.random()*10)+1}}return die}),result=evaluateTest(dice,record.difficulty);setCharacter(current=>current?{...current,data:{...current.data,willpowerSuperficial:Math.min(willpowerMax-current.data.willpowerAggravated,current.data.willpowerSuperficial+1),rollHistory:(current.data.rollHistory||[]).map(item=>item.id===record.id?{...item,dice,...result,rerolled:true}:item)}}:current)};
  const rouseCheck=()=>{const value=Math.floor(Math.random()*10)+1,success=value>=6,nextHunger=success?character.data.hunger:Math.min(5,character.data.hunger+1);if(nextHunger!==character.data.hunger)setData("hunger",nextHunger);recordRoll({id:crypto.randomUUID(),kind:"rouse",label:"Teste de Despertar",pool:1,hunger:0,difficulty:1,dice:[{value,hunger:false}],successes:success?1:0,outcome:success?"Sucesso — Fome não aumenta":character.data.hunger>=5?"Falha — Fome já está em 5":"Falha — Fome +1",createdAt:new Date().toISOString()})};
  return <main className="play-shell">
    <header className="play-topbar"><div className="play-brand"><span>C</span><div><strong>CARNIÇAL</strong><small>MODO DE JOGO</small></div></div><nav><Link href="/"><ArrowLeft size={15}/>Criação</Link><Link href="/rules"><BookOpen size={15}/>Biblioteca</Link></nav><div className="play-account"><span className={status==="error"?"save-error":""}>{status==="saving"?"Salvando…":status==="error"?"Falha ao salvar":"Salvo"}</span><span>{displayName}</span><a href={signOutPath} target="_top"><LogOut size={16}/></a></div></header>
    <div className="play-layout">
      <aside className="play-roster"><span>PERSONAGEM EM JOGO</span><select value={character.id} onChange={event=>selectCharacter(Number(event.target.value))}>{characters.map(item=><option value={item.id} key={item.id}>{item.name||"Sem nome"} — {item.clan||"Sem Clã"}</option>)}</select><div className="play-portrait">{(character.name||"?")[0]}</div><h1>{character.name||"Sem nome"}</h1><p>{character.concept||"Conceito não definido"}</p><dl><div><dt>Clã</dt><dd>{character.clan||"—"}</dd></div><div><dt>Predador</dt><dd>{character.data.predator||"—"}</dd></div><div><dt>Geração</dt><dd>{character.data.generation}</dd></div><div><dt>Potência</dt><dd>{character.data.bloodPotency}</dd></div></dl>{character.data.clanBane&&<div className="play-warning"><CircleAlert size={15}/><div><strong>Fraqueza do Clã</strong><p>{character.data.clanBane}</p></div></div>}</aside>
      <section className="play-main">
        <div className="play-heading"><div><span>{character.data.chronicle||"CRÔNICA NÃO DEFINIDA"}</span><h2>A noite de {character.name||"seu personagem"}</h2></div><div className="play-heading-actions"><button className="play-audit-button" onClick={()=>setAuditOpen(true)}><CircleAlert size={16}/><span>Incoerências</span><b>{auditIssues.filter(issue=>issue.kind==="warning").length}</b></button><div className="xp-card"><span>XP gasto / total</span><strong>{xpSpent(character.data.xpSpent,character.data.xpPurchases)} / {xpBudget(character.data.xpTotal,character.data.ageCategory||"")}</strong></div></div></div>
        <div className="session-trackers">
          <DamageTrack label="Vitalidade" max={healthMax} superficial={character.data.healthSuperficial} aggravated={character.data.healthAggravated} onChange={(superficial,aggravated)=>setCharacter(current=>current?{...current,data:{...current.data,healthSuperficial:superficial,healthAggravated:aggravated}}:current)}/>
          <DamageTrack label="Força de Vontade" max={willpowerMax} superficial={character.data.willpowerSuperficial} aggravated={character.data.willpowerAggravated} onChange={(superficial,aggravated)=>setCharacter(current=>current?{...current,data:{...current.data,willpowerSuperficial:superficial,willpowerAggravated:aggravated}}:current)}/>
          <Counter label="Fome" value={character.data.hunger} min={0} max={5} onChange={value=>setData("hunger",value)} accent/>
          <Counter label="Humanidade" value={character.data.humanity} min={1} max={10} onChange={value=>setData("humanity",value)}/>
          <Counter label="Máculas" value={character.data.stains} min={0} max={10} onChange={value=>setData("stains",value)}/>
        </div>
        <section className="dice-console" id="dice-console"><div className="dice-console-head"><div><span>ROLADOR V5</span><h3>Parada com Dados de Fome</h3></div><Link href="/rules?book=core-v5&chapter=regras-e-criacao-sangue-fome-geracao-e-potencia-de-sangue&q=Dados%20de%20Fome"><BookOpen size={14}/>Abrir regra</Link></div>
          <div className="pool-builder"><label><span>Característica 1 <em>Opcional</em></span><select value={rollTraitA} onChange={event=>setRollTraitA(event.target.value)}><option value="">Parada manual</option><TraitOptions items={traitOptions}/></select></label><span className="pool-plus">+</span><label><span>Característica 2 <em>Opcional</em></span><select value={rollTraitB} onChange={event=>setRollTraitB(event.target.value)}><option value="">Nenhuma</option><TraitOptions items={traitOptions} exclude={rollTraitA}/></select></label><label><span>Modificador</span><input type="number" min={-10} max={10} value={rollModifier} onChange={event=>setRollModifier(Number(event.target.value))}/></label><div className="pool-total"><span>Parada calculada</span><strong>{builtPool}</strong></div></div>
          {selectedSpecialties.length>0&&<label className="specialty-toggle"><input type="checkbox" checked={useSpecialty} onChange={event=>setUseSpecialty(event.target.checked)}/><span>Aplicar especialização (+1): {selectedSpecialties.map(item=>item.name).join(", ")}</span></label>}
          <div className="dice-controls"><label><span>Ação <em>Opcional</em></span><input value={rollLabel} onChange={event=>setRollLabel(event.target.value)} placeholder={defaultRollLabel||"Ex.: investigar a cena"}/></label>{selectedTraits.length===0&&<label><span>Parada manual</span><input type="number" min={1} max={30} value={rollPool} onChange={event=>setRollPool(Number(event.target.value))}/></label>}<label><span>Dificuldade</span><input type="number" min={1} max={10} value={rollDifficulty} onChange={event=>setRollDifficulty(Number(event.target.value))}/></label><div className="hunger-readout"><span>Dados de Fome</span><strong>{Math.min(builtPool,character.data.hunger)}</strong><small>Fome atual {character.data.hunger}</small></div><button className="roll-button" onClick={rollTest}><Dices size={18}/>Rolar {builtPool} dados</button><button className="rouse-button" onClick={rouseCheck}>Teste de Despertar</button></div>
          {(character.data.rollHistory||[]).length>0&&<div className="roll-history">{(character.data.rollHistory||[]).slice(0,5).map((record,index)=><article key={record.id}><div className="roll-result-head"><div><span>{record.label}</span><strong>{record.outcome}</strong></div><small>{record.kind==="test"?`${record.successes} sucesso(s) · Dif. ${record.difficulty}${typeof record.margin==="number"?` · Margem ${record.margin>=0?"+":""}${record.margin}`:""}`:"1 dado"}</small></div><div className="rolled-dice">{record.dice.map((die,dieIndex)=><i key={dieIndex} className={`${die.hunger?"hunger":"normal"}${die.value===1?" one":""}${die.value===10?" ten":""}`}>{die.value}</i>)}</div>{index===0&&record.kind==="test"&&!record.rerolled&&record.dice.some(die=>!die.hunger&&die.value<6)&&character.data.willpowerSuperficial+character.data.willpowerAggravated<willpowerMax&&<button className="reroll-button" onClick={()=>rerollWillpower(record)}><RefreshCcw size={14}/>Rerrolar até 3 falhas normais (1 Vontade)</button>}{record.rerolled&&<small className="reroll-used">Rerrolagem de Vontade usada</small>}</article>)}</div>}
        </section>
        <Tabs defaultValue="traits" className="play-tabs"><TabsList variant="line"><TabsTrigger value="traits">Características</TabsTrigger><TabsTrigger value="disciplines">Disciplinas</TabsTrigger><TabsTrigger value="story">Âncoras</TabsTrigger><TabsTrigger value="notes">Notas</TabsTrigger></TabsList>
          <TabsContent value="traits"><div className="play-columns"><TraitPanel title="Atributos" values={character.data.attributes}/><TraitPanel title="Habilidades" values={character.data.skills} specialties={specialtiesBySkill}/></div></TabsContent>
          <TabsContent value="disciplines"><div className="play-disciplines">{Object.entries(character.data.disciplines).filter(([,dots])=>dots>0).map(([name,dots])=><article key={name}><header><h3>{name}</h3><DotsRead value={dots}/></header>{(character.data.disciplinePowers[name]||[]).filter(Boolean).map(power=><p key={power}><Sparkles size={14}/>{power}</p>)}</article>)}</div></TabsContent>
          <TabsContent value="story"><div className="play-story"><StoryBlock title="Ambição" text={character.data.ambition}/><StoryBlock title="Desejo" text={character.data.desire}/><StoryBlock title="Convicções" text={character.data.convictions}/><StoryBlock title="Pilares" text={character.data.touchstones}/><StoryBlock title="Vantagens" text={character.data.merits.map(item=>`${item.name} ${"•".repeat(item.dots)}`).join("\n")}/><StoryBlock title="Defeitos" text={character.data.flawItems.map(item=>`${item.name} ${"•".repeat(item.dots)}`).join("\n")}/></div></TabsContent>
          <TabsContent value="notes"><label className="play-notes"><span>Notas da sessão</span><textarea value={character.data.notes} onChange={event=>setData("notes",event.target.value)} placeholder="Condições, lembretes, dívidas e acontecimentos desta noite…"/></label></TabsContent>
        </Tabs>
      </section>
    </div>
    <nav className="play-mobile-actions" aria-label="Ações do modo de jogo">
      <Link href="/"><ArrowLeft size={20}/><span>Criação</span></Link>
      <Link href="/rules"><BookOpen size={20}/><span>Regras</span></Link>
      <button type="button" onClick={()=>setAuditOpen(true)}><CircleAlert size={20}/><span>Alertas</span>{auditIssues.filter(issue=>issue.kind==="warning").length>0&&<b>{auditIssues.filter(issue=>issue.kind==="warning").length}</b>}</button>
      <button type="button" className="mobile-primary" onClick={()=>document.getElementById("dice-console")?.scrollIntoView({behavior:"smooth",block:"start"})}><Dices size={20}/><span>Rolar</span></button>
    </nav>
    <InconsistencySheet open={auditOpen} onOpenChange={setAuditOpen} issues={auditIssues} onToggleApproval={(id,approved)=>setData("chronicleRules",{...character.data.chronicleRules,approvedIssueIds:approved?[...new Set([...character.data.chronicleRules.approvedIssueIds,id])]:character.data.chronicleRules.approvedIssueIds.filter(item=>item!==id)})}/>
  </main>;
}

function Counter({label,value,min,max,onChange,accent=false}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void;accent?:boolean}){return <div className={accent?"counter-card accent":"counter-card"}><span>{label}</span><div><button aria-label={`Diminuir ${label}`} onClick={()=>onChange(Math.max(min,value-1))} disabled={value<=min}><Minus size={16}/></button><strong>{value}</strong><button aria-label={`Aumentar ${label}`} onClick={()=>onChange(Math.min(max,value+1))} disabled={value>=max}><Plus size={16}/></button></div><div className="counter-dots">{Array.from({length:max},(_,i)=><i className={i<value?"filled":""} key={i}/>)}</div></div>}
function DamageTrack({label,max,superficial,aggravated,onChange}:{label:string;max:number;superficial:number;aggravated:number;onChange:(s:number,a:number)=>void}){const total=Math.min(max,superficial+aggravated);return <div className="damage-card"><header><span>{label}</span><strong>{total}/{max}</strong></header><div className="damage-boxes">{Array.from({length:max},(_,i)=><i key={i} className={i<aggravated?"aggravated":i<aggravated+superficial?"superficial":""}>{i<aggravated?"×":i<aggravated+superficial?"/":""}</i>)}</div><div className="damage-actions"><span>Superficial</span><button aria-label={`Remover dano superficial de ${label}`} disabled={superficial<=0} onClick={()=>onChange(Math.max(0,superficial-1),aggravated)}><Minus size={16}/></button><button aria-label={`Adicionar dano superficial a ${label}`} disabled={total>=max} onClick={()=>onChange(Math.min(max-aggravated,superficial+1),aggravated)}><Plus size={16}/></button><span>Agravado</span><button aria-label={`Remover dano agravado de ${label}`} disabled={aggravated<=0} onClick={()=>onChange(superficial,Math.max(0,aggravated-1))}><Minus size={16}/></button><button aria-label={`Adicionar dano agravado a ${label}`} disabled={total>=max} onClick={()=>onChange(Math.min(superficial,max-(aggravated+1)),Math.min(max,aggravated+1))}><Plus size={16}/></button></div></div>}
function TraitPanel({title,values,specialties={}}:{title:string;values:Values;specialties?:Partial<Record<string,Specialty[]>>}){return <section className="trait-panel"><h3>{title}</h3>{Object.entries(values).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><span>{name}{specialties[name]?.length?<small>{specialties[name]?.map(item=>item.name).join(", ")}</small>:null}</span><DotsRead value={value}/></div>)}</section>}
function DotsRead({value}:{value:number}){return <span className="dots-read">{Array.from({length:5},(_,i)=><i className={i<value?"filled":""} key={i}/>)}</span>}
function StoryBlock({title,text}:{title:string;text:string}){return <article><span>{title}</span>{text?<p>{text}</p>:<em>Não preenchido</em>}</article>}
function TraitOptions({items,exclude}:{items:Array<{key:string;name:string;value:number;group:string}>;exclude?:string}){return <>{["Atributos","Habilidades","Disciplinas"].map(group=><optgroup label={group} key={group}>{items.filter(item=>item.group===group&&item.key!==exclude).map(item=><option value={item.key} key={item.key}>{item.name} ({item.value})</option>)}</optgroup>)}</>}
