"use client";
import { readAnchors } from "../anchors";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, BookOpen, CircleAlert, Dices, LogOut, Minus, Plus, Shield } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { migrateLegacyData } from "../legacy-migration";
import { auditCharacter } from "../character-audit";
import { InconsistencySheet } from "../inconsistency-sheet";
import { DEFAULT_CHRONICLE_RULES, type ChronicleRules } from "../game-rules";
import { xpBudget, xpSpent, type XpPurchase } from "../experience";
import { evaluateTest, rollPool as generatePool, rerollDice, resolveRouseCheck, humanityTrack, resolveRemorse, frenzyPool, type RollRecord } from "./dice";
import { advanceNight, bloodBenefits, bloodSession, eligibleAggravated, mendSuperficial, recoverAggravated, type BloodSession } from "./blood";
import RollHistory from "./roll-history";
import HumanityTrack from "./humanity-track";
import PowerDetails from "./power-details";

type Values=Record<string,number>;
type Specialty={skill:string;name:string;source:string};
type Merit={name:string;dots:number;source:string;notes:string};
type GameData={
  attributes:Values;skills:Values;disciplines:Values;disciplinePowers:Record<string,string[]>;specialties:Specialty[];merits:Merit[];flawItems:Merit[];
  bloodSession?:BloodSession;stainImpaired?:boolean;predator:string;humanity:number;hunger:number;stains:number;healthSuperficial:number;healthAggravated:number;willpowerSuperficial:number;willpowerAggravated:number;
  convictions:string;touchstones:string;ambition:string;desire:string;clanBane:string;clanCompulsion:string;resonance:string;bloodPotency:number;generation:string;
  xpTotal:string;xpSpent:string;xpPurchases:XpPurchase[];chronicle:string;notes:string;ageCategory?:string;skillPreset?:string;predatorApplied?:string;predatorDiscipline?:string;predatorResolutions?:Record<string,string>;chronicleRules:ChronicleRules;allowHomebrew?:boolean;rollHistory?:RollRecord[];[key:string]:unknown;
};
type Character={id:number;name:string;concept:string;clan:string;sourcebook:string;data:GameData;chronicleId?:string|null};
const defaults:GameData={attributes:{},skills:{},disciplines:{},disciplinePowers:{},specialties:[],merits:[],flawItems:[],predator:"",humanity:7,hunger:1,stains:0,healthSuperficial:0,healthAggravated:0,willpowerSuperficial:0,willpowerAggravated:0,convictions:"",touchstones:"",ambition:"",desire:"",clanBane:"",clanCompulsion:"",resonance:"",bloodPotency:1,generation:"13ª",xpTotal:"",xpSpent:"",xpPurchases:[],chronicle:"",notes:"",chronicleRules:{...DEFAULT_CHRONICLE_RULES}};
const normalize=(value:Character):Character=>({...value,data:migrateLegacyData({...defaults,...(value.data||{}),attributes:value.data?.attributes||{},skills:value.data?.skills||{},disciplines:value.data?.disciplines||{},disciplinePowers:value.data?.disciplinePowers||{},specialties:value.data?.specialties||[],merits:value.data?.merits||[],flawItems:value.data?.flawItems||[],xpPurchases:value.data?.xpPurchases||[],predatorResolutions:value.data?.predatorResolutions||{},chronicleRules:{...DEFAULT_CHRONICLE_RULES,...(value.data?.chronicleRules||{})}}).data as GameData});


export default function GameSheet({displayName,signOutPath}:{displayName:string;signOutPath:string}){
  const [characters,setCharacters]=useState<Character[]>([]),[character,setCharacter]=useState<Character|null>(null),[status,setStatus]=useState<"loading"|"saved"|"saving"|"error">("loading"),[auditOpen,setAuditOpen]=useState(false),[rollPool,setRollPool]=useState(5),[rollDifficulty,setRollDifficulty]=useState(3),[rollLabel,setRollLabel]=useState(""),[rollTraitA,setRollTraitA]=useState(""),[rollTraitB,setRollTraitB]=useState(""),[rollModifier,setRollModifier]=useState(0),[useSpecialty,setUseSpecialty]=useState(false);
  const persisted=useRef("");
  const latest=useRef(character),saving=useRef(false); useEffect(()=>{latest.current=character},[character]);
  const [useSurge,setUseSurge]=useState(false),[manualAttribute,setManualAttribute]=useState(false);
  const [frenzyDifficulty,setFrenzyDifficulty]=useState(3);
  useEffect(()=>{fetch("/api/characters").then(async response=>{if(!response.ok)throw new Error();return await response.json() as {characters:Character[]}}).then(({characters})=>{const safe=characters.map(normalize);setCharacters(safe);const requested=Number(new URLSearchParams(window.location.search).get("id"));const initial=safe.find(item=>item.id===requested)??safe[0]??null;setCharacter(initial);persisted.current=JSON.stringify(initial);setStatus("saved")}).catch(()=>setStatus("error"))},[]);
  useEffect(()=>{if(!character||JSON.stringify(character)===persisted.current)return;
    const timer=setTimeout(async()=>{if(saving.current)return;saving.current=true;setStatus("saving");
      try{while(latest.current&&JSON.stringify(latest.current)!==persisted.current){
        const snapshot=latest.current,serialized=JSON.stringify(snapshot);
        const response=await fetch(`/api/characters/${snapshot.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:serialized});
        if(!response.ok)throw new Error();
        const {character:saved}=await response.json() as {character:Character};const safe=normalize(saved);
        persisted.current=serialized;
        if(latest.current?.id===snapshot.id&&JSON.stringify(latest.current)===serialized){
          latest.current=safe;persisted.current=JSON.stringify(safe);setCharacter(safe);
        }
        setCharacters(items=>items.map(item=>item.id===safe.id?(latest.current?.id===safe.id?latest.current:safe):item));
      }setStatus("saved")}catch{setStatus("error")}finally{saving.current=false}
    },600);return()=>clearTimeout(timer)
  },[character]);
  const setData=<K extends keyof GameData>(key:K,value:GameData[K])=>setCharacter(current=>current?{...current,data:{...current.data,[key]:value}}:current);
  const selectCharacter=(id:number)=>{if(saving.current||JSON.stringify(character)!==persisted.current)return;setUseSurge(false);const next=characters.find(item=>item.id===id)??null;setCharacter(next);persisted.current=JSON.stringify(next);history.replaceState(null,"",`/play?id=${id}`)};
  const healthMax=(character?.data.attributes.Vigor||1)+3,willpowerMax=(character?.data.attributes.Autocontrole||1)+(character?.data.attributes.Determinação||1);
  const specialtiesBySkill=useMemo(()=>Object.groupBy(character?.data.specialties||[],item=>item.skill),[character]);
  const auditIssues=useMemo(()=>character?auditCharacter({name:character.name,concept:character.concept,clan:character.clan,data:character.data}):[],[character]);
  const traitOptions=useMemo(()=>{if(!character)return[];return[
    ...Object.entries(character.data.attributes).filter(([,value])=>value>0).map(([name,value])=>({key:`attribute:${name}`,name,value,group:"Atributos"})),
    ...Object.entries(character.data.skills).filter(([,value])=>value>0).map(([name,value])=>({key:`skill:${name}`,name,value,group:"Habilidades"})),
    ...Object.entries(character.data.disciplines).filter(([,value])=>value>0).map(([name,value])=>({key:`discipline:${name}`,name,value,group:"Disciplinas"})),
  ]},[character]);
  if(status==="loading")return <main className="play-loading">Abrindo ficha…</main>;
  if(!character)return <main className="play-empty"><Shield size={38}/><h1>Nenhuma ficha disponível</h1><p>Crie um personagem antes de abrir o modo de jogo.</p><Link href="/">Criar personagem</Link></main>;
  const selectedTraits=[traitOptions.find(item=>item.key===rollTraitA),traitOptions.find(item=>item.key===rollTraitB)].filter(Boolean) as typeof traitOptions;
  const selectedSpecialties=selectedTraits.flatMap(item=>item.group==="Habilidades"?(specialtiesBySkill[item.name]||[]):[]);
  const moralTrack={...humanityTrack(character.data.humanity,character.data.stains),impaired:!!character.data.stainImpaired||humanityTrack(character.data.humanity,character.data.stains).impaired};
  const session=bloodSession(character.data.bloodSession),benefits=bloodBenefits(character.data.bloodPotency);
  const surgeAllowed=selectedTraits.some(item=>item.group==="Atributos")||(!selectedTraits.length&&manualAttribute);
  const surgeActive=useSurge&&surgeAllowed;
  const basePool=selectedTraits.length?selectedTraits.reduce((total,item)=>total+item.value,0)+rollModifier+(useSpecialty&&selectedSpecialties.length?1:0):rollPool;
  const builtPool=Math.max(1,Math.min(30,basePool+(surgeActive?benefits.surge:0)-(moralTrack.impaired?2:0)));
  const resistPool=Math.max(1,frenzyPool(willpowerMax,character.data.willpowerSuperficial,character.data.willpowerAggravated,character.data.humanity)-(moralTrack.impaired&&!character.data.chronicleRules.exemptStainPenaltyOnFrenzy?2:0));
  const changeMorality=(humanity:number,stains:number)=>setCharacter(current=>{if(!current)return current;
    const oldOverflow=humanityTrack(current.data.humanity,current.data.stains).overflow,newTrack=humanityTrack(humanity,stains);
    const added=Math.max(0,newTrack.overflow-oldOverflow),aggravated=Math.min(willpowerMax,current.data.willpowerAggravated+added);
    return {...current,data:{...current.data,humanity,stains,stainImpaired:!!current.data.stainImpaired||oldOverflow>0||newTrack.impaired,willpowerAggravated:aggravated,willpowerSuperficial:Math.min(current.data.willpowerSuperficial,willpowerMax-aggravated)}}
  });
  const changeStains=(stains:number)=>changeMorality(character.data.humanity,stains);
  const acceptHumanityLoss=()=>{if(!window.confirm("Perder 1 Humanidade para limpar as Máculas e encerrar a debilitação? O dano em Vontade permanece."))return;setCharacter(current=>current?{...current,data:{...current.data,humanity:Math.max(0,current.data.humanity-1),stains:0,stainImpaired:false}}:current)};
  const remorseCheck=()=>{const values=Array.from({length:10},()=>Math.random()),id=crypto.randomUUID(),createdAt=new Date().toISOString();let index=0;setCharacter(current=>{index=0;if(!current||(current.data.stains<=0&&!current.data.stainImpaired)||current.data.humanity<=0)return current;const pool=humanityTrack(current.data.humanity,current.data.stains).remorsePool,dice=generatePool(pool,0,()=>values[index++]),resolved=resolveRemorse(current.data.humanity,dice),result=evaluateTest(dice,1),record:RollRecord={id,kind:"remorse",label:"Teste de Remorso",pool,hunger:0,difficulty:1,dice,...result,outcome:resolved.outcome,explanation:`Humanidade ${current.data.humanity} → ${resolved.humanity}. Todas as Máculas foram apagadas. Sem dados de Fome ou rerrolagem por Vontade.`,createdAt};return {...current,data:{...current.data,humanity:resolved.humanity,stains:0,stainImpaired:false,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}})};
  const resistFrenzy=()=>{const dice=resistPool?generatePool(resistPool,0):[],difficulty=Math.max(1,Math.min(10,Math.trunc(frenzyDifficulty)||1)),result=evaluateTest(dice,difficulty);recordRoll({id:crypto.randomUUID(),kind:"frenzy",label:"Resistência ao Frenesi",pool:resistPool,hunger:0,difficulty,dice,...result,outcome:result.successes>=difficulty?result.pairs>0?"Frenesi resistido — sem perder um turno":"Frenesi resistido — um turno para conter o impulso":"Falha — sucumbe ao Frenesi",explanation:`Vontade limpa ${Math.max(0,willpowerMax-character.data.willpowerSuperficial-character.data.willpowerAggravated)} + Humanidade ${Math.floor(character.data.humanity/3)}${moralTrack.impaired&&!character.data.chronicleRules.exemptStainPenaltyOnFrenzy?" − 2 por Máculas":""} = ${resistPool} dado(s), mínimo 1. Sem Fome, Impulso ou rerrolagem por Vontade. O mestre conduz as consequências.`,createdAt:new Date().toISOString()})};
  const defaultRollLabel=selectedTraits.map(item=>item.name).join(" + ");
  const recordRoll=(record:RollRecord)=>setCharacter(current=>current?{...current,data:{...current.data,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}:current);
  const rollTest=()=>{if(session.torpor||(surgeActive&&character.data.hunger>=5))return;
    const rouseDie=Math.floor(Math.random()*10)+1,dice=generatePool(builtPool,character.data.hunger),pool=dice.length,hunger=dice.filter(die=>die.hunger).length,difficulty=Math.max(1,Math.min(10,Math.trunc(rollDifficulty)||1)),result=evaluateTest(dice,difficulty);
    const record:RollRecord={id:crypto.randomUUID(),kind:"test",label:rollLabel.trim()||defaultRollLabel||"Teste",pool,hunger,difficulty,dice,...result,explanation:surgeActive?`Impulso +${benefits.surge} dados (Potência ${character.data.bloodPotency}). Sangue: ${rouseDie}. ${resolveRouseCheck(character.data.hunger,rouseDie).outcome}. O aumento de Fome ocorre após esta rolagem.`:undefined,createdAt:new Date().toISOString()};
    setCharacter(current=>{if(!current||bloodSession(current.data.bloodSession).torpor||(surgeActive&&current.data.hunger>=5))return current;return {...current,data:{...current.data,hunger:surgeActive?resolveRouseCheck(current.data.hunger,rouseDie).hunger:current.data.hunger,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}});
    setUseSurge(false);
  };
  const rerollWillpower=(record:RollRecord,indices:number[])=>{const dice=rerollDice(record.dice,indices);if(!dice)return;const result=evaluateTest(dice,record.difficulty);setCharacter(current=>{if(!current||record.kind!=="test"||record.id!==current.data.rollHistory?.[0]?.id||current.data.rollHistory[0].rerolled||current.data.willpowerSuperficial+current.data.willpowerAggravated>=willpowerMax)return current;return{...current,data:{...current.data,willpowerSuperficial:current.data.willpowerSuperficial+1,rollHistory:(current.data.rollHistory||[]).map(item=>item.id===record.id?{...item,dice,...result,rerolled:true}:item)}}})};
  const bloodRecord=(kind:RollRecord["kind"],label:string,values:number[],outcome:string,explanation:string):RollRecord=>({id:crypto.randomUUID(),kind,label,pool:values.length,hunger:0,difficulty:1,dice:values.map(value=>({value,hunger:false})),successes:values.filter(value=>value>=6).length,outcome,explanation,createdAt:new Date().toISOString()});
  const rouseCheck=()=>{const value=Math.floor(Math.random()*10)+1;setCharacter(current=>{if(!current||current.data.hunger>=5||bloodSession(current.data.bloodSession).torpor)return current;const result=resolveRouseCheck(current.data.hunger,value),record=bloodRecord("rouse","Incitar o Sangue",[value],result.outcome,"Uso voluntário. Não substitui o despertar de uma nova noite.");return {...current,data:{...current.data,hunger:result.hunger,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}})};
  const mend=()=>{const die=Math.floor(Math.random()*10)+1;setCharacter(current=>{if(!current)return current;const result=mendSuperficial(bloodSession(current.data.bloodSession),current.data.healthSuperficial,current.data.hunger,current.data.bloodPotency,die);if(!result)return current;const healed=current.data.healthSuperficial-result.damage,record=bloodRecord("mend","Recuperar Vitalidade superficial",[die],`${healed} dano(s) recuperado(s)`,result.check.outcome);return {...current,data:{...current.data,healthSuperficial:result.damage,hunger:result.hunger,bloodSession:result.session,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}})};
  const newNight=()=>{if(!window.confirm("Avançar para a próxima noite e realizar o teste obrigatório de despertar? Confirme com o Narrador."))return;const die=Math.floor(Math.random()*10)+1;setCharacter(current=>{if(!current)return current;const result=advanceNight(bloodSession(current.data.bloodSession),current.data.hunger,die);if(!result)return current;const record=bloodRecord("awakening",`Despertar — noite ${result.session.night+1}`,[die],result.check.outcome,"Teste obrigatório ao despertar. Fome acima de 5 leva ao Torpor.");return {...current,data:{...current.data,hunger:result.hunger,bloodSession:result.session,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}})};
  const mendAggravated=()=>{const dice=Array.from({length:3},()=>Math.floor(Math.random()*10)+1);setCharacter(current=>{if(!current||!current.data.healthAggravated)return current;const result=recoverAggravated(bloodSession(current.data.bloodSession),current.data.hunger,dice);if(!result)return current;const record=bloodRecord("aggravated","Recuperar Vitalidade agravada",dice.slice(0,result.checks.length),result.healed?"1 dano agravado recuperado":"Torpor — recuperação interrompida",result.checks.map((check,i)=>`Sangue ${i+1}: ${check.outcome}`).join(". "));return {...current,data:{...current.data,healthAggravated:current.data.healthAggravated-(result.healed?1:0),hunger:result.hunger,bloodSession:result.session,rollHistory:[record,...(current.data.rollHistory||[])].slice(0,20)}}})};
  const damageVitality=(superficial:number,aggravated:number)=>setCharacter(current=>{if(!current)return current;const session=bloodSession(current.data.bloodSession),nights=[...session.aggravatedNights];if(aggravated>current.data.healthAggravated)nights.push(...Array.from({length:aggravated-current.data.healthAggravated},()=>session.night));else if(aggravated<current.data.healthAggravated)nights.splice(0,current.data.healthAggravated-aggravated);return {...current,data:{...current.data,healthSuperficial:superficial,healthAggravated:aggravated,bloodSession:{...session,aggravatedNights:nights}}}});
  return <main className="play-shell">
    <header className="play-topbar"><div className="play-brand"><span>C</span><div><strong>CARNIÇAL</strong><small>MODO DE JOGO</small></div></div><nav><Link href="/"><ArrowLeft size={15}/>Criação</Link><Link href="/rules"><BookOpen size={15}/>Biblioteca</Link><Link href="/chronicles">Crônicas</Link></nav><div className="play-account"><span className={status==="error"?"save-error":""}>{status==="saving"?"Salvando…":status==="error"?"Falha ao salvar":"Salvo"}</span>{status==="error"&&<button onClick={()=>setCharacter(current=>current?{...current}:current)}>Tentar salvar novamente</button>}<span>{displayName}</span><a href={signOutPath} target="_top"><LogOut size={16}/></a></div></header>
    <div className="play-layout">
      <aside className="play-roster"><span>PERSONAGEM EM JOGO</span><select disabled={status!=="saved"} value={character.id} onChange={event=>selectCharacter(Number(event.target.value))}>{characters.map(item=><option value={item.id} key={item.id}>{item.name||"Sem nome"} — {item.clan||"Sem Clã"}</option>)}</select><div className="play-portrait">{(character.name||"?")[0]}</div><h1>{character.name||"Sem nome"}</h1><p>{character.concept||"Conceito não definido"}</p><dl><div><dt>Clã</dt><dd>{character.clan||"—"}</dd></div><div><dt>Predador</dt><dd>{character.data.predator||"—"}</dd></div><div><dt>Geração</dt><dd>{character.data.generation}</dd></div><div><dt>Potência</dt><dd>{character.data.bloodPotency}</dd></div></dl>{character.data.clanBane&&<div className="play-warning"><CircleAlert size={15}/><div><strong>Fraqueza do Clã</strong><p>{character.data.clanBane}</p></div></div>}</aside>
      <section className="play-main">
        <div className="play-heading"><div><span>{character.data.chronicle||"CRÔNICA NÃO DEFINIDA"}</span><h2>A noite de {character.name||"seu personagem"}</h2></div><div className="play-heading-actions"><button className="play-audit-button" onClick={()=>setAuditOpen(true)}><CircleAlert size={16}/><span>Incoerências</span><b>{auditIssues.filter(issue=>issue.kind==="warning").length}</b></button><div className="xp-card"><span>XP gasto / total</span><strong>{xpSpent(character.data.xpSpent,character.data.xpPurchases)} / {xpBudget(character.data.xpTotal,character.data.ageCategory||"")}</strong></div></div></div>
        <div className="session-trackers">
          <DamageTrack label="Vitalidade" max={healthMax} superficial={character.data.healthSuperficial} aggravated={character.data.healthAggravated} onChange={damageVitality}/>
          <DamageTrack label="Força de Vontade" max={willpowerMax} superficial={character.data.willpowerSuperficial} aggravated={character.data.willpowerAggravated} onChange={(superficial,aggravated)=>setCharacter(current=>current?{...current,data:{...current.data,willpowerSuperficial:superficial,willpowerAggravated:aggravated}}:current)}/>
          <Counter label="Fome" value={character.data.hunger} min={0} max={5} onChange={value=>setData("hunger",value)} accent/>
          <HumanityTrack impaired={moralTrack.impaired} humanity={character.data.humanity} stains={character.data.stains} onHumanityChange={value=>changeMorality(value,character.data.stains)} onStainsChange={changeStains}/>
        </div>
        {character.data.willpowerAggravated>=willpowerMax&&<p role="alert" className="chronicle-error">Força de Vontade totalmente preenchida com dano agravado: em um conflito social, o personagem está fora do conflito. Fora dele, não há efeito imediato adicional além da Debilitação. O Narrador determina as consequências (Livro Básico, p. 127).</p>}
        {character.data.humanity===0&&<p role="alert" className="chronicle-error">Humanidade zero: o personagem passa ao controle do Narrador.</p>}
        <section className="blood-tools"><h3>Sangue e recuperação</h3><p>Potência {character.data.bloodPotency}: Impulso +{benefits.surge} · Recuperação superficial {benefits.mend}. Noite {session.night+1} · Turno {session.turn+1}.</p><p><a href="https://renegadegamestudios.com/content/File%20Storage%20for%20site/VTM/BloodPotencyTable.pdf" target="_blank" rel="noreferrer">Tabela oficial corrigida</a> · Livro Básico, pp. 211, 218–219.</p>
          <div className="blood-actions"><button disabled={session.torpor} onClick={()=>setData("bloodSession",{...session,turn:session.turn+1})}>Avançar turno</button><button disabled={session.torpor||character.data.hunger>=5||!character.data.healthSuperficial||session.lastMendTurn===session.turn} onClick={mend}>Recuperar superficial ({benefits.mend})</button><button disabled={session.torpor} onClick={newNight}>Nova noite e despertar</button><button disabled={!character.data.healthAggravated||!eligibleAggravated(session)||session.aggravatedNights.length!==character.data.healthAggravated} onClick={mendAggravated}>Recuperar 1 agravado (3 testes)</button></div>
          <p>Superficial: uma vez por turno. Agravado: uma vez por noite, a partir da noite seguinte ao dano. Fome 5 impede usos voluntários.</p>
          {character.data.healthAggravated>session.aggravatedNights.length&&<div><p>Há dano agravado antigo sem registro de noite. Quando ocorreu? Confirme com o Narrador.</p><button onClick={()=>setData("bloodSession",{...session,aggravatedNights:[...session.aggravatedNights,...Array.from({length:character.data.healthAggravated-session.aggravatedNights.length},()=>session.night-1)]})}>Em uma noite anterior</button><button onClick={()=>setData("bloodSession",{...session,aggravatedNights:[...session.aggravatedNights,...Array.from({length:character.data.healthAggravated-session.aggravatedNights.length},()=>session.night)]})}>Nesta noite</button></div>}
          {session.torpor&&<div role="alert"><p>Torpor: o despertar ou a recuperação exigiria Fome acima de 5. A saída do Torpor é decidida com o Narrador.</p><button onClick={()=>{if(window.confirm("O Narrador autorizou a saída do Torpor? Ajuste a Fome conforme a alimentação e as regras."))setData("bloodSession",{...session,torpor:false})}}>Registrar saída do Torpor</button></div>}
        </section>
        <section className="dice-console" id="dice-console"><div className="dice-console-head"><div><span>ROLADOR V5</span><h3>Parada com Dados de Fome</h3></div><Link href="/rules?book=core-v5&chapter=regras-e-criacao-sangue-fome-geracao-e-potencia-de-sangue&q=Dados%20de%20Fome"><BookOpen size={14}/>Abrir regra</Link></div>
          <div className="pool-builder"><label><span>Característica 1 <em>Opcional</em></span><select value={rollTraitA} onChange={event=>setRollTraitA(event.target.value)}><option value="">Parada manual</option><TraitOptions items={traitOptions}/></select></label><span className="pool-plus">+</span><label><span>Característica 2 <em>Opcional</em></span><select value={rollTraitB} onChange={event=>setRollTraitB(event.target.value)}><option value="">Nenhuma</option><TraitOptions items={traitOptions} exclude={rollTraitA}/></select></label><label><span>Modificador</span><input type="number" min={-10} max={10} value={rollModifier} onChange={event=>setRollModifier(Number(event.target.value))}/></label><div className="pool-total"><span>Parada calculada</span><strong>{builtPool}</strong></div></div>
          {selectedSpecialties.length>0&&<label className="specialty-toggle"><input type="checkbox" checked={useSpecialty} onChange={event=>setUseSpecialty(event.target.checked)}/><span>Aplicar especialização (+1): {selectedSpecialties.map(item=>item.name).join(", ")}</span></label>}
          {!selectedTraits.length&&<label className="specialty-toggle"><input type="checkbox" checked={manualAttribute} onChange={event=>setManualAttribute(event.target.checked)}/>A parada manual inclui Atributo</label>}
          <label className="specialty-toggle"><input type="checkbox" checked={surgeActive} disabled={!surgeAllowed||character.data.hunger>=5||session.torpor} onChange={event=>setUseSurge(event.target.checked)}/>Impulso de Sangue (+{benefits.surge} dados, um teste de Sangue). Apenas esta rolagem.</label>
          <div className="dice-controls"><label><span>Ação <em>Opcional</em></span><input value={rollLabel} onChange={event=>setRollLabel(event.target.value)} placeholder={defaultRollLabel||"Ex.: investigar a cena"}/></label>{selectedTraits.length===0&&<label><span>Parada manual</span><input type="number" min={1} max={30} value={rollPool} onChange={event=>setRollPool(Number(event.target.value))}/></label>}<label><span>Dificuldade</span><input type="number" min={1} max={10} value={rollDifficulty} onChange={event=>setRollDifficulty(Number(event.target.value))}/></label><div className="hunger-readout"><span>Dados de Fome</span><strong>{Math.min(builtPool,character.data.hunger)}</strong><small>Fome atual {character.data.hunger}</small></div><button className="roll-button" disabled={session.torpor||(surgeActive&&character.data.hunger>=5)} onClick={rollTest}><Dices size={18}/>Rolar {builtPool} dados</button><button className="rouse-button" disabled={session.torpor||character.data.hunger>=5} onClick={rouseCheck}>Incitar o Sangue</button></div>
          <div className="moral-tests"><div><h4>Teste de Remorso</h4><p>{moralTrack.remorsePool} dado(s) · Dificuldade 1 · Sem Fome. Ao final da sessão, com Máculas: sucesso mantém Humanidade; falha perde 1. Ambos apagam as Máculas.</p><button disabled={(!character.data.stains&&!moralTrack.impaired)||!character.data.humanity} onClick={remorseCheck}>Rolar Remorso e atualizar ficha</button></div><div><h4>Resistir ao Frenesi</h4><p>{resistPool} dado(s) · Vontade restante + ⌊Humanidade ÷ 3⌋{moralTrack.impaired&&!character.data.chronicleRules.exemptStainPenaltyOnFrenzy?" − 2 por Debilitado (p. 239)":""} · Sem Fome.</p><label>Dificuldade do mestre<input type="number" min={1} max={10} value={frenzyDifficulty} onChange={event=>setFrenzyDifficulty(Number(event.target.value))}/></label><button disabled={!character.data.humanity||session.torpor} onClick={resistFrenzy}>Testar resistência ao Frenesi</button></div></div>
          {moralTrack.impaired&&<button disabled={!character.data.humanity} onClick={acceptHumanityLoss}>Perder 1 Humanidade e limpar Máculas</button>}
          {moralTrack.impaired&&<p role="alert" className="chronicle-error">Debilitado pelas Máculas: −2 dados em todas as paradas (Livro Básico, p. 239). O excesso causa dano agravado à Vontade. A condição termina com Remorso ou perda voluntária de Humanidade; o dano permanece.</p>}
          <p className="dice-legend"><span><b className="normal-key"/>Dados comuns</span><span><b className="hunger-key"/>Dados de Fome · vermelhos</span><span>6–10: sucesso · par de 10: 4 sucessos</span></p>
          <p className="dice-hunger-help">A Fome substitui dados comuns; não aumenta a parada. Um 10 de Fome só causa crítico bestial se houver um crítico e o teste passar. Um 1 de Fome só causa falha bestial se o teste falhar.</p>
          <RollHistory key={character.id} records={character.data.rollHistory||[]} canRerollLatest={character.data.rollHistory?.[0]?.kind==="test"&&!character.data.rollHistory[0].rerolled&&character.data.rollHistory[0].dice.some(die=>!die.hunger)&&character.data.willpowerSuperficial+character.data.willpowerAggravated<willpowerMax} onReroll={rerollWillpower} onClear={()=>setData("rollHistory",[])}/>
        </section>
        <Tabs defaultValue="traits" className="play-tabs"><TabsList variant="line"><TabsTrigger value="traits">Características</TabsTrigger><TabsTrigger value="disciplines">Disciplinas</TabsTrigger><TabsTrigger value="story">Âncoras</TabsTrigger><TabsTrigger value="notes">Notas</TabsTrigger></TabsList>
          <TabsContent value="traits"><div className="play-columns"><TraitPanel title="Atributos" values={character.data.attributes}/><TraitPanel title="Habilidades" values={character.data.skills} specialties={specialtiesBySkill}/></div></TabsContent>
          <TabsContent value="disciplines"><div className="play-disciplines">{Object.entries(character.data.disciplines).filter(([,dots])=>dots>0).map(([name,dots])=><article key={name}><header><h3>{name}</h3><DotsRead value={dots}/></header>{(character.data.disciplinePowers[name]||[]).filter(Boolean).map(power=><PowerDetails key={power} name={power} discipline={name}/>)}</article>)}</div></TabsContent>
          <TabsContent value="story"><div className="play-story"><StoryBlock title="Ambição" text={character.data.ambition}/><StoryBlock title="Desejo" text={character.data.desire}/>{readAnchors(character.data.touchstones,character.data.convictions).map((anchor,index)=><StoryBlock key={index} title={`Pilar + Convicção ${index+1}`} text={`Pilar: ${anchor.touchstone||"Não preenchido"}\nConvicção: ${anchor.conviction||"Não preenchida"}`}/>)}<StoryBlock title="Vantagens" text={character.data.merits.map(item=>`${item.name} ${"•".repeat(item.dots)}`).join("\n")}/><StoryBlock title="Defeitos" text={character.data.flawItems.map(item=>`${item.name} ${"•".repeat(item.dots)}`).join("\n")}/></div></TabsContent>
          <TabsContent value="notes"><label className="play-notes"><span>Notas da sessão</span><textarea value={character.data.notes} onChange={event=>setData("notes",event.target.value)} placeholder="Condições, lembretes, dívidas e acontecimentos desta noite…"/></label></TabsContent>
        </Tabs>
      </section>
    </div>
    <nav className="play-mobile-actions" aria-label="Ações do modo de jogo">
      <Link href="/"><ArrowLeft size={20}/><span>Criação</span></Link>
      <Link href="/rules"><BookOpen size={20}/><span>Regras</span></Link>
      <button type="button" onClick={()=>setAuditOpen(true)}><CircleAlert size={20}/><span>Alertas</span>{auditIssues.filter(issue=>issue.kind==="warning").length>0&&<b>{auditIssues.filter(issue=>issue.kind==="warning").length}</b>}</button>
      <button type="button" className="mobile-primary" onClick={()=>document.getElementById("dice-console")?.scrollIntoView({behavior:"smooth",block:"start"})}><Dices size={20}/><span>Rolar</span></button>
    </nav>
    <InconsistencySheet open={auditOpen} onOpenChange={setAuditOpen} issues={auditIssues} onToggleApproval={character.chronicleId?undefined:(id,approved)=>setData("chronicleRules",{...character.data.chronicleRules,approvedIssueIds:approved?[...new Set([...character.data.chronicleRules.approvedIssueIds,id])]:character.data.chronicleRules.approvedIssueIds.filter(item=>item!==id)})}/>
  </main>;
}

function Counter({label,value,min,max,onChange,accent=false}:{label:string;value:number;min:number;max:number;onChange:(value:number)=>void;accent?:boolean}){return <div className={accent?"counter-card accent":"counter-card"}><span>{label}</span><div><button aria-label={`Diminuir ${label}`} onClick={()=>onChange(Math.max(min,value-1))} disabled={value<=min}><Minus size={16}/></button><strong>{value}</strong><button aria-label={`Aumentar ${label}`} onClick={()=>onChange(Math.min(max,value+1))} disabled={value>=max}><Plus size={16}/></button></div><div className="counter-dots">{Array.from({length:max},(_,i)=><i className={i<value?"filled":""} key={i}/>)}</div></div>}
function DamageTrack({label,max,superficial,aggravated,onChange}:{label:string;max:number;superficial:number;aggravated:number;onChange:(s:number,a:number)=>void}){const total=Math.min(max,superficial+aggravated);return <div className="damage-card"><header><span>{label}</span><strong>{total}/{max}</strong></header><div className="damage-boxes">{Array.from({length:max},(_,i)=><i key={i} className={i<aggravated?"aggravated":i<aggravated+superficial?"superficial":""}>{i<aggravated?"×":i<aggravated+superficial?"/":""}</i>)}</div><div className="damage-actions"><span>Superficial</span><button aria-label={`Remover dano superficial de ${label}`} disabled={superficial<=0} onClick={()=>onChange(Math.max(0,superficial-1),aggravated)}><Minus size={16}/></button><button aria-label={`Adicionar dano superficial a ${label}`} disabled={total>=max} onClick={()=>onChange(Math.min(max-aggravated,superficial+1),aggravated)}><Plus size={16}/></button><span>Agravado</span><button aria-label={`Remover dano agravado de ${label}`} disabled={aggravated<=0} onClick={()=>onChange(superficial,Math.max(0,aggravated-1))}><Minus size={16}/></button><button aria-label={`Adicionar dano agravado a ${label}`} disabled={total>=max} onClick={()=>onChange(Math.min(superficial,max-(aggravated+1)),Math.min(max,aggravated+1))}><Plus size={16}/></button></div></div>}
function TraitPanel({title,values,specialties={}}:{title:string;values:Values;specialties?:Partial<Record<string,Specialty[]>>}){return <section className="trait-panel"><h3>{title}</h3>{Object.entries(values).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1]).map(([name,value])=><div key={name}><span>{name}{specialties[name]?.length?<small>{specialties[name]?.map(item=>item.name).join(", ")}</small>:null}</span><DotsRead value={value}/></div>)}</section>}
function DotsRead({value}:{value:number}){return <span className="dots-read">{Array.from({length:5},(_,i)=><i className={i<value?"filled":""} key={i}/>)}</span>}
function StoryBlock({title,text}:{title:string;text:string}){return <article><span>{title}</span>{text?<p>{text}</p>:<em>Não preenchido</em>}</article>}
function TraitOptions({items,exclude}:{items:Array<{key:string;name:string;value:number;group:string}>;exclude?:string}){return <>{["Atributos","Habilidades","Disciplinas"].map(group=><optgroup label={group} key={group}>{items.filter(item=>item.group===group&&item.key!==exclude).map(item=><option value={item.key} key={item.key}>{item.name} ({item.value})</option>)}</optgroup>)}</>}
