"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { BookOpen, Check, ChevronLeft, ChevronRight, CircleAlert, Dna, Feather, LogOut, Menu, Plus, Save, ScrollText, ShieldCheck, Sparkles, Trash2, UserRound, X } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { AGE_RULES, DEFAULT_CHRONICLE_RULES, POWER_CATALOG, PREDATOR_RULES, SKILL_PRESETS, rulesUrl, type ChronicleRules } from "./game-rules";
import { migrateLegacyData } from "./legacy-migration";
import { auditCharacter } from "./character-audit";
import { InconsistencySheet } from "./inconsistency-sheet";

type Values = Record<string, number>;
type Specialty = { skill: string; name: string; source: string };
type Merit = { name: string; dots: number; source: string; notes: string };
type CharacterData = {
  sire:string; mortalName:string; embraceYear:string; chronicle:string; customClan:string; ageCategory:string; generation:string; bloodPotency:number;
  attributes:Values; skills:Values; skillPreset:string; specialties:Specialty[]; disciplines:Values; disciplinePowers:Record<string,string[]>;
  predator:string; advantages:string; flaws:string; merits:Merit[]; flawItems:Merit[]; convictions:string; touchstones:string;
  ambition:string; desire:string; humanity:number; notes:string; allowHomebrew:boolean; clanBane:string; clanCompulsion:string;
  resonance:string; hunger:number; chronicleTenets:string; xpTotal:string; xpSpent:string; trueAge:string; apparentAge:string;
  predatorApplied:string; predatorDiscipline:string; predatorSpecialty:string;
  predatorResolutions:Record<string,string>;chronicleRules:ChronicleRules;
  birthDate:string; deathDate:string; appearance:string; distinguishingTraits:string; history:string;
};
type Character = { id?:number; name:string; concept:string; clan:string; sourcebook:string; data:CharacterData };
type StatusKind = "required"|"optional"|"conditional"|"chronicle";

declare global { interface Document { modelContext?: { registerTool(tool:{name:string;title?:string;description:string;inputSchema:object;annotations?:{readOnlyHint?:boolean;untrustedContentHint?:boolean};execute(input:unknown):unknown|Promise<unknown>},options?:{signal?:AbortSignal}):void|Promise<void> } } }

const ATTRIBUTES=["Força","Destreza","Vigor","Carisma","Manipulação","Autocontrole","Inteligência","Raciocínio","Determinação"];
const SKILLS=["Atletismo","Briga","Furtividade","Armas Brancas","Armas de Fogo","Condução","Ladroagem","Ofícios","Sobrevivência","Empatia com Animais","Etiqueta","Intimidação","Liderança","Manha","Performance","Persuasão","Sagacidade","Subterfúgio","Ciência","Erudição","Finanças","Investigação","Medicina","Ocultismo","Percepção","Política","Tecnologia"];
const STEPS=[{name:"Identidade",icon:UserRound},{name:"Linhagem",icon:Dna},{name:"Atributos",icon:Sparkles},{name:"Habilidades",icon:Feather},{name:"Disciplinas",icon:Sparkles},{name:"Predador",icon:BookOpen},{name:"Vantagens",icon:Plus},{name:"Crenças",icon:ShieldCheck},{name:"Crônica",icon:ScrollText},{name:"Revisão",icon:Check}];
const CLANS:[string,string,string[]][]=[
  ["Brujah","core_v5_ptbr",["Celeridade","Potência","Presença"]],["Gangrel","core_v5_ptbr",["Animalismo","Fortitude","Proteanismo"]],
  ["Malkaviano","core_v5_ptbr",["Auspícios","Dominação","Ofuscação"]],["Nosferatu","core_v5_ptbr",["Animalismo","Ofuscação","Potência"]],
  ["Toreador","core_v5_ptbr",["Auspícios","Celeridade","Presença"]],["Tremere","core_v5_ptbr",["Auspícios","Dominação","Feitiçaria de Sangue"]],
  ["Ventrue","core_v5_ptbr",["Dominação","Fortitude","Presença"]],["Lasombra","chicago_by_night_v5",["Dominação","Oblívio","Potência"]],
  ["Caitiff","core_v5_ptbr",["Duas Disciplinas quaisquer"]],["Sangue-Ralo","core_v5_ptbr",["Sem Disciplinas intrínsecas"]],
];
const PREDATORS=["Consensualista","Fazendeiro","Osíris","Sacoleiro","Sandman","Sanguessuga","Scene Queen","Sereia","Trinchador","Vira-lata"];
const blankValues=(names:string[],value=0)=>Object.fromEntries(names.map(name=>[name,value]));
const emptyData=():CharacterData=>({sire:"",mortalName:"",embraceYear:"",chronicle:"",customClan:"",ageCategory:"Criança da Noite",generation:"13ª",bloodPotency:1,attributes:blankValues(ATTRIBUTES,2),skills:blankValues(SKILLS),skillPreset:"Equilibrado",specialties:[],disciplines:{},disciplinePowers:{},predator:"",advantages:"",flaws:"",merits:[],flawItems:[],convictions:"",touchstones:"",ambition:"",desire:"",humanity:7,notes:"",allowHomebrew:true,clanBane:"",clanCompulsion:"",resonance:"",hunger:0,chronicleTenets:"",xpTotal:"",xpSpent:"",trueAge:"",apparentAge:"",birthDate:"",deathDate:"",appearance:"",distinguishingTraits:"",history:"",predatorApplied:"",predatorDiscipline:"",predatorSpecialty:"",predatorResolutions:{},chronicleRules:{...DEFAULT_CHRONICLE_RULES}});
const blankCharacter=():Character=>({name:"",concept:"",clan:"",sourcebook:"core_v5_ptbr",data:emptyData()});
function normalizeCharacter(value:Character):Character{const base={...emptyData(),...(value.data||{}),attributes:{...blankValues(ATTRIBUTES,2),...(value.data?.attributes||{})},skills:{...blankValues(SKILLS),...(value.data?.skills||{})},specialties:value.data?.specialties||[],disciplines:value.data?.disciplines||{},disciplinePowers:value.data?.disciplinePowers||{},merits:value.data?.merits||[],flawItems:value.data?.flawItems||[],predatorResolutions:value.data?.predatorResolutions||{},chronicleRules:{...DEFAULT_CHRONICLE_RULES,...(value.data?.chronicleRules||{})}};const migrated=migrateLegacyData(base).data;return{...blankCharacter(),...value,data:migrated}}

function Dots({value,onChange,max=5,min=0,label}:{value:number;onChange:(v:number)=>void;max?:number;min?:number;label:string}){return <div className="dots" role="group" aria-label={`${label}: ${value} pontos`}>{Array.from({length:max},(_,i)=>{const dot=i+1;return <button type="button" key={dot} aria-label={`${dot} pontos`} onClick={()=>onChange(value===dot?min:dot)} className={dot<=value?"dot active":"dot"}/>})}</div>}
function Status({kind}:{kind:StatusKind}){const labels={required:"Obrigatório",optional:"Opcional",conditional:"Condicional",chronicle:"Da crônica"};return <em className={`field-status ${kind}`}>{labels[kind]}</em>}
function Field({label,value,onChange,placeholder="",wide=false,status="optional"}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;wide?:boolean;status?:StatusKind}){return <label className={wide?"field wide":"field"}><span>{label}<Status kind={status}/></span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function TextArea({label,value,onChange,placeholder,status="optional"}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string;status?:StatusKind}){return <label className="field wide"><span>{label}<Status kind={status}/></span><textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}

export default function CharacterStudio({displayName,signOutPath,previewMode=false}:{displayName:string;signOutPath:string;previewMode?:boolean}){
  const [characters,setCharacters]=useState<Character[]>([]),[character,setCharacter]=useState<Character>(blankCharacter),[step,setStep]=useState(0),[status,setStatus]=useState<"loading"|"saved"|"saving"|"error">(previewMode?"saved":"loading"),[mobileNav,setMobileNav]=useState(false),[sourcesOpen,setSourcesOpen]=useState(false),[auditOpen,setAuditOpen]=useState(false);
  const hydrated=useRef(previewMode),lastPersisted=useRef("");
  useEffect(()=>{if(previewMode)return;fetch("/api/characters").then(async r=>{if(!r.ok)throw new Error();return await r.json() as {characters:Character[]}}).then(({characters})=>{const safe=characters.map(normalizeCharacter),initial=safe[0]??blankCharacter();setCharacters(safe);setCharacter(initial);lastPersisted.current=JSON.stringify(initial);setStatus("saved");hydrated.current=true;for(let i=0;i<characters.length;i++){if(characters[i].id&&JSON.stringify(characters[i].data)!==JSON.stringify(safe[i].data)){void fetch(`/api/characters/${characters[i].id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(safe[i])})}}}).catch(()=>{setStatus("error");hydrated.current=true})},[previewMode]);
  const save=useCallback(async(next:Character)=>{setStatus("saving");try{const response=await fetch(next.id?`/api/characters/${next.id}`:"/api/characters",{method:next.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!response.ok)throw new Error();const {character:savedRaw}=await response.json() as {character:Character},saved=normalizeCharacter(savedRaw);lastPersisted.current=JSON.stringify(saved);setCharacter(saved);setCharacters(items=>[saved,...items.filter(item=>item.id!==saved.id)]);setStatus("saved")}catch{setStatus("error")}},[]);
  useEffect(()=>{if(previewMode||!hydrated.current||JSON.stringify(character)===lastPersisted.current)return;const timer=setTimeout(()=>save(character),850);return()=>clearTimeout(timer)},[character,previewMode,save]);
  const setTop=(key:keyof Pick<Character,"name"|"concept"|"clan"|"sourcebook">,value:string)=>setCharacter(c=>({...c,[key]:value}));
  const setData=<K extends keyof CharacterData>(key:K,value:CharacterData[K])=>setCharacter(c=>({...c,data:{...c.data,[key]:value}}));
  const setNested=(key:"attributes"|"skills"|"disciplines",name:string,value:number)=>setCharacter(c=>({...c,data:{...c.data,[key]:{...c.data[key],[name]:value}}}));
  const attrCounts=useMemo<Values>(()=>Object.values(character.data.attributes).reduce<Values>((a,v)=>{a[v]=(a[v]||0)+1;return a},{}),[character.data.attributes]);
  const clanInfo=CLANS.find(([name])=>name===character.clan),selectedSource=clanInfo?.[1]??(character.clan==="Personalizado"?"custom":character.sourcebook);
  const skillCounts=Object.values(character.data.skills).reduce<Values>((a,v)=>{if(v>0)a[v]=(a[v]||0)+1;return a},{}),skillTarget=SKILL_PRESETS[character.data.skillPreset];
  const skillsValid=!skillTarget||Object.entries(skillTarget).every(([level,count])=>(skillCounts[Number(level)]||0)===count)&&Object.values(skillCounts).reduce((a,b)=>a+b,0)===Object.values(skillTarget).reduce((a,b)=>a+b,0);
  const predatorRule=PREDATOR_RULES.find(rule=>rule.name===character.data.predator),appliedPredator=PREDATOR_RULES.find(rule=>rule.name===character.data.predatorApplied);
  const ageRule=AGE_RULES[character.data.ageCategory],ageValid=!ageRule||character.clan==="Sangue-Ralo"||(ageRule.generations.includes(character.data.generation)&&character.data.bloodPotency===ageRule.bloodPotency+(appliedPredator?.bloodPotency||0));
  const disciplineDots=Object.values(character.data.disciplines).reduce((a,b)=>a+b,0),meritDots=character.data.merits.reduce((a,b)=>a+b.dots,0),flawDots=character.data.flawItems.reduce((a,b)=>a+b.dots,0);
  const auditIssues=useMemo(()=>auditCharacter(character),[character]);
  const chronicle=character.data.chronicleRules,meritTarget=chronicle.customTargets?chronicle.meritPoints:7,flawTarget=chronicle.customTargets?chronicle.flawPoints:2,disciplineTarget=chronicle.customTargets?chronicle.disciplinePoints:3;
  const predatorResolved=!predatorRule||predatorRule.resolutions.every(item=>!item.required||!!character.data.predatorResolutions[item.id]);
  const validations=[{ok:!!character.name.trim(),text:"Nome do personagem"},{ok:!!character.concept.trim(),text:"Conceito definido"},{ok:!!character.clan.trim(),text:"Clã ou linhagem"},{ok:attrCounts[4]===1&&attrCounts[3]===3&&attrCounts[2]===4&&attrCounts[1]===1,text:"Atributos: 1/3/4/1"},{ok:skillsValid,text:`Habilidades: ${character.data.skillPreset}`},{ok:chronicle.generationOverride||ageValid,text:"Idade, Geração e Potência compatíveis"},{ok:character.clan==="Sangue-Ralo"||disciplineDots===disciplineTarget+(character.data.predatorApplied?1:0),text:`Disciplinas iniciais: ${disciplineTarget}, mais Predador`},{ok:!!character.data.predator&&character.data.predatorApplied===character.data.predator&&predatorResolved,text:"Pacote de Predador resolvido"},{ok:meritDots===meritTarget,text:`Vantagens: ${meritTarget} pontos`},{ok:flawDots>=flawTarget,text:`Defeitos: ao menos ${flawTarget} pontos`},{ok:character.data.convictions.split("\n").filter(Boolean).length===character.data.touchstones.split("\n").filter(Boolean).length&&!!character.data.convictions.trim(),text:"Convicções ligadas a Pilares"}],completed=validations.filter(v=>v.ok).length;
  const selectClan=(name:string,source:string,disciplines:string[])=>setCharacter(c=>({...c,clan:name,sourcebook:source,data:{...c.data,disciplines:name==="Sangue-Ralo"?{}:Object.fromEntries(disciplines.filter(x=>!x.includes("quaisquer")).map(x=>[x,0])),clanBane:name==="Lasombra"?"Reflexos e gravações ficam distorcidos; tecnologia de comunicação exige teste de Tecnologia com dificuldade 2 + Severidade da Fraqueza.":c.data.clanBane,clanCompulsion:name==="Lasombra"?"Implacabilidade: após falhar, sofre penalidade de dois dados até ter sucesso em nova tentativa da mesma ação.":c.data.clanCompulsion}}));
  const updateMerit=(key:"merits"|"flawItems",index:number,patch:Partial<Merit>)=>setData(key,character.data[key].map((m,i)=>i===index?{...m,...patch}:m)),addMerit=(key:"merits"|"flawItems")=>setData(key,[...character.data[key],{name:"",dots:1,source:"core_v5_ptbr",notes:""}]),removeMerit=(key:"merits"|"flawItems",index:number)=>setData(key,character.data[key].filter((_,i)=>i!==index));
  const applyPredator=()=>{if(!predatorRule||!character.data.predatorDiscipline||!character.data.predatorSpecialty)return;setCharacter(c=>{const already=c.data.predatorApplied===predatorRule.name;const disciplines={...c.data.disciplines};if(!already)disciplines[c.data.predatorDiscipline]=(disciplines[c.data.predatorDiscipline]||0)+1;const source=`predator:${predatorRule.id}`;const specialties=c.data.specialties.some(item=>item.source===source)?c.data.specialties:[...c.data.specialties,{skill:c.data.predatorSpecialty,name:"Especialização do Predador",source}];return{...c,data:{...c.data,disciplines,specialties,humanity:already?c.data.humanity:Math.max(1,c.data.humanity+predatorRule.humanity),bloodPotency:already?c.data.bloodPotency:c.data.bloodPotency+predatorRule.bloodPotency,predatorApplied:predatorRule.name}}})};
  const choosePredator=(name:string)=>setCharacter(c=>{const previous=PREDATOR_RULES.find(rule=>rule.name===c.data.predatorApplied),disciplines={...c.data.disciplines};let specialties=c.data.specialties,humanity=c.data.humanity,bloodPotency=c.data.bloodPotency;if(previous){const appliedDiscipline=c.data.predatorDiscipline;if(appliedDiscipline&&disciplines[appliedDiscipline]>0)disciplines[appliedDiscipline]-=1;specialties=specialties.filter(item=>item.source!==`predator:${previous.id}`);humanity=Math.max(1,humanity-previous.humanity);bloodPotency=Math.max(0,bloodPotency-previous.bloodPotency)}return{...c,data:{...c.data,predator:name,predatorApplied:"",predatorDiscipline:"",predatorSpecialty:"",predatorResolutions:{},disciplines,specialties,humanity,bloodPotency}}});
  const setChronicleRule=<K extends keyof ChronicleRules>(key:K,value:ChronicleRules[K])=>setData("chronicleRules",{...character.data.chronicleRules,[key]:value});
  const toggleApproval=(id:string,approved:boolean)=>setCharacter(current=>{const currentIds=current.data.chronicleRules.approvedIssueIds;return{...current,data:{...current.data,chronicleRules:{...current.data.chronicleRules,approvedIssueIds:approved?[...new Set([...currentIds,id])]:currentIds.filter(item=>item!==id)}}}});
  useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"start_character_creation",title:"Iniciar criação de personagem",description:"Abre uma nova ficha V5 vazia.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){setCharacter(blankCharacter());setStep(0);return{status:"ready",step:"Identidade"}}},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort()},[]);

  return <main className="studio-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark">N</div><div><strong>NOCTIS</strong><span>ARQUIVO DE PERSONAGENS</span></div></div><div className="save-state"><span className={status==="error"?"status-dot error":"status-dot"}/>{previewMode?"Prévia local":status==="saving"?"Salvando…":status==="error"?"Falha ao salvar":status==="loading"?"Abrindo arquivo…":"Salvo"}</div><div className="user-area"><Link className="mode-link" href={character.id?`/play?id=${character.id}`:"/play"}>Modo de jogo</Link><span>{displayName}</span><a href={signOutPath} target="_top" title="Sair"><LogOut size={17}/></a></div><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Abrir navegação"><Menu/></button></header>
    <div className="workspace">
      <aside className={`left-rail ${mobileNav?"open":""}`}><div className="rail-heading"><span>SUAS FICHAS</span><button onClick={()=>{setCharacter(blankCharacter());setStep(0)}}><Plus size={16}/></button></div><div className="character-list">{characters.length===0&&<p className="empty-copy">Sua primeira ficha aparecerá aqui quando você começar a preencher.</p>}{characters.map(item=><button key={item.id} className={item.id===character.id?"character-item active":"character-item"} onClick={()=>{setCharacter(normalizeCharacter(item));setStep(0);setMobileNav(false)}}><span className="portrait-seal">{(item.name||"?")[0]}</span><span><strong>{item.name||"Sem nome"}</strong><small>{item.clan||"Linhagem indefinida"}</small></span></button>)}</div><div className="step-nav"><span>CRIAÇÃO</span>{STEPS.map((item,index)=><button key={item.name} className={index===step?"active":index<step?"done":""} onClick={()=>{setStep(index);setMobileNav(false)}}><item.icon size={16}/><span>{item.name}</span>{index<step&&<Check size={14}/>}</button>)}</div><div className="rail-links"><Link className="rulebook-link mobile-mode-link" href={character.id?`/play?id=${character.id}`:"/play"}><Sparkles size={16}/>Modo de jogo</Link><button className="rulebook-link" onClick={()=>{setAuditOpen(true);setMobileNav(false)}}><CircleAlert size={16}/>Incoerências <b>{auditIssues.filter(issue=>issue.kind==="warning").length}</b></button><button className="rulebook-link" onClick={()=>setSourcesOpen(true)}><BookOpen size={16}/>Fontes e regras</button></div></aside>
      <section className="editor"><div className="editor-kicker"><span>ETAPA {step+1} DE {STEPS.length}</span><span>{Math.round((step+1)/STEPS.length*100)}% DO PERCURSO</span></div><div className="progress-track"><span style={{width:`${(step+1)/STEPS.length*100}%`}}/></div>
        {step===0&&<Section title="Quem você deixou para trás?" subtitle="Comece pela pessoa. Os números vêm depois."><div className="form-grid"><Field label="Nome atual" status="required" value={character.name} onChange={v=>setTop("name",v)} placeholder="Como a noite o conhece"/><Field label="Nome mortal" value={character.data.mortalName} onChange={v=>setData("mortalName",v)}/><Field wide label="Conceito central" status="required" value={character.concept} onChange={v=>setTop("concept",v)}/><Field label="Crônica" status="chronicle" value={character.data.chronicle} onChange={v=>setData("chronicle",v)}/><Field label="Ano do Abraço" value={character.data.embraceYear} onChange={v=>setData("embraceYear",v)}/><Field wide label="Senhor" value={character.data.sire} onChange={v=>setData("sire",v)}/><Field label="Idade real" value={character.data.trueAge} onChange={v=>setData("trueAge",v)}/><Field label="Idade aparente" value={character.data.apparentAge} onChange={v=>setData("apparentAge",v)}/><Field label="Data de nascimento" value={character.data.birthDate} onChange={v=>setData("birthDate",v)}/><Field label="Data da morte" value={character.data.deathDate} onChange={v=>setData("deathDate",v)}/></div></Section>}
        {step===1&&<Section title="O Sangue carrega uma herança" subtitle="Escolha uma linhagem oficial ou escreva a sua própria."><div className="source-filter"><span>FONTES ATIVAS</span><button className="source-chip active" onClick={()=>setSourcesOpen(true)}>Livro Básico V5</button><button className="source-chip chicago" onClick={()=>setSourcesOpen(true)}>Chicago by Night</button></div><div className="clan-grid">{CLANS.map(([name,source,disciplines])=><button key={name} className={character.clan===name?"clan-card selected":"clan-card"} onClick={()=>selectClan(name,source,disciplines)}><div><strong>{name}</strong><em className={source==="chicago_by_night_v5"?"source chicago":"source"}>{source==="chicago_by_night_v5"?"CHICAGO":"BÁSICO"}</em></div><p>{disciplines.join(", ")}</p></button>)}<button className={character.clan==="Personalizado"?"clan-card selected custom":"clan-card custom"} onClick={()=>selectClan("Personalizado","custom",[])}><div><strong>Personalizado</strong><em className="source custom">HOMEBREW</em></div><p>Defina linhagem, Disciplinas e regras livremente.</p></button></div>{character.clan==="Personalizado"&&<Field wide label="Nome da linhagem" status="required" value={character.data.customClan} onChange={v=>setData("customClan",v)}/>}<div className="form-grid compact"><label className="field"><span>Categoria de idade<Status kind="required"/></span><select value={character.data.ageCategory} onChange={e=>setData("ageCategory",e.target.value)}><option>Criança da Noite</option><option>Neófito</option><option>Ancilla</option><option>Personalizada</option></select></label><Field label="Geração" status="required" value={character.data.generation} onChange={v=>setData("generation",v)}/><label className="field"><span>Potência de Sangue<Status kind="required"/></span><Dots label="Potência de Sangue" max={5} value={character.data.bloodPotency} onChange={v=>setData("bloodPotency",v)}/></label></div><TextArea label="Fraqueza do Clã" status="conditional" value={character.data.clanBane} onChange={v=>setData("clanBane",v)} placeholder="Preenchida quando a fonte foi normalizada; editável pela crônica."/><TextArea label="Compulsão do Clã" status="conditional" value={character.data.clanCompulsion} onChange={v=>setData("clanCompulsion",v)} placeholder="Preenchida quando disponível."/></Section>}
        {step===2&&<Section title="Defina suas capacidades" subtitle="Distribua 1 Atributo em 4, 3 em 3, 4 em 2 e 1 em 1."><div className="attribute-summary"><span className={attrCounts[4]===1?"ok":""}>Nível 4 <b>{attrCounts[4]||0}/1</b></span><span className={attrCounts[3]===3?"ok":""}>Nível 3 <b>{attrCounts[3]||0}/3</b></span><span className={attrCounts[2]===4?"ok":""}>Nível 2 <b>{attrCounts[2]||0}/4</b></span><span className={attrCounts[1]===1?"ok":""}>Nível 1 <b>{attrCounts[1]||0}/1</b></span></div><TraitGroup title="FÍSICOS" names={ATTRIBUTES.slice(0,3)} values={character.data.attributes} onChange={(n,v)=>setNested("attributes",n,Math.max(1,v))}/><TraitGroup title="SOCIAIS" names={ATTRIBUTES.slice(3,6)} values={character.data.attributes} onChange={(n,v)=>setNested("attributes",n,Math.max(1,v))}/><TraitGroup title="MENTAIS" names={ATTRIBUTES.slice(6)} values={character.data.attributes} onChange={(n,v)=>setNested("attributes",n,Math.max(1,v))}/><div className="derived"><div><span>Vitalidade</span><strong>{(character.data.attributes.Vigor||1)+3}</strong><small>Vigor + 3</small></div><div><span>Força de Vontade</span><strong>{(character.data.attributes.Autocontrole||1)+(character.data.attributes.Determinação||1)}</strong><small>Autocontrole + Determinação</small></div></div></Section>}
        {step===3&&<Section title="O que você aprendeu?" subtitle="Distribua Habilidades e registre Especializações separadamente.">
          <div className="preset-row">{["Pau pra toda obra","Equilibrado","Especialista","Livre"].map(p=><button key={p} onClick={()=>setData("skillPreset",p)} className={character.data.skillPreset===p?"preset active":"preset"}>{p}</button>)}</div>
          {skillTarget&&<div className={skillsValid?"rule-status ok":"rule-status warning"}><div><strong>{skillsValid?"Distribuição concluída":"Distribuição em andamento"}</strong><p>{Object.entries(skillTarget).sort((a,b)=>Number(b[0])-Number(a[0])).map(([level,count])=>`${count} em ${level} (${skillCounts[Number(level)]||0}/${count})`).join(" · ")}</p></div><Link href="/rules?book=core-v5&chapter=regras-e-criacao-atributos-habilidades-e-especializacoes&q=Distribuições rápidas">Ver regra</Link></div>}
          <div className="skill-grid">{SKILLS.map(name=><div className="trait" key={name}><span>{name}</span><Dots label={name} value={character.data.skills[name]||0} onChange={v=>setNested("skills",name,v)}/></div>)}</div>
          <ListHeading title="Especializações" copy="O nome permanece livre; a origem fica registrada." onAdd={()=>setData("specialties",[...character.data.specialties,{skill:SKILLS[0],name:"",source:"core_v5_ptbr"}])}/>
          {character.data.specialties.map((s,i)=><div className="inline-editor" key={i}><select value={s.skill} onChange={e=>setData("specialties",character.data.specialties.map((x,j)=>j===i?{...x,skill:e.target.value}:x))}>{SKILLS.map(x=><option key={x}>{x}</option>)}</select><input value={s.name} onChange={e=>setData("specialties",character.data.specialties.map((x,j)=>j===i?{...x,name:e.target.value}:x))} placeholder="Nome da especialização"/><SourceSelect value={s.source} onChange={source=>setData("specialties",character.data.specialties.map((x,j)=>j===i?{...x,source}:x))}/><button onClick={()=>setData("specialties",character.data.specialties.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}
        </Section>}
        {step===4&&<Section title="O Sangue responde" subtitle="Na criação padrão, escolha duas Disciplinas do Clã: uma em 2 e outra em 1.">
          <div className="discipline-grid">{Object.keys(character.data.disciplines).map(name=><div className="discipline-card" key={name}><div><strong>{name}</strong><em className={name==="Oblívio"?"source chicago":"source"}>{name==="Oblívio"?"CHICAGO":"BÁSICO"}</em></div><Dots label={name} value={character.data.disciplines[name]||0} onChange={v=>setNested("disciplines",name,v)}/><PowerPicker discipline={name} level={character.data.disciplines[name]||0} selected={character.data.disciplinePowers[name]||[]} onChange={powers=>setData("disciplinePowers",{...character.data.disciplinePowers,[name]:powers})}/></div>)}</div>
          {(character.clan==="Caitiff"||character.clan==="Personalizado")&&<button className="add-wide" onClick={()=>{const name=prompt("Nome da Disciplina");if(name)setNested("disciplines",name,0)}}><Plus size={15}/>Adicionar Disciplina personalizada</button>}
          <RuleNote>Os catálogos do Livro Básico indexam nome, nível, Amálgama e páginas verificadas. O efeito completo permanece na biblioteca; poderes personalizados continuam permitidos.</RuleNote>
        </Section>}
        {step===5&&<Section title="Como você caça?" subtitle="O Tipo de Predador modifica a ficha, mas não limita outras formas de alimentação.">
          <div className="predator-list">{PREDATORS.map(name=><button key={name} onClick={()=>character.data.predator!==name&&choosePredator(name)} className={character.data.predator===name?"predator selected":"predator"}><span className="radio-mark"/><span><strong>{name}</strong><small>{predatorDescription(name)}</small></span></button>)}</div>
          {predatorRule&&<div className="predator-package"><div className="package-head"><div><span>PACOTE DE PREDADOR</span><strong>{predatorRule.name}</strong></div><Link href={rulesUrl(predatorRule.source)}>Abrir regra</Link></div><div className="form-grid"><label className="field"><span>Disciplina concedida<Status kind="required"/></span><select value={character.data.predatorDiscipline} onChange={e=>setData("predatorDiscipline",e.target.value)}><option value="">Escolha…</option>{predatorRule.disciplineChoices.map(item=><option key={item}>{item}</option>)}</select></label><label className="field"><span>Habilidade da Especialização<Status kind="required"/></span><select value={character.data.predatorSpecialty} onChange={e=>setData("predatorSpecialty",e.target.value)}><option value="">Escolha…</option>{predatorRule.specialtyChoices.map(item=><option key={item}>{item}</option>)}</select></label></div><div className="package-effects">{predatorRule.humanity!==0&&<span>{predatorRule.humanity>0?"+":""}{predatorRule.humanity} Humanidade</span>}{predatorRule.bloodPotency!==0&&<span>+{predatorRule.bloodPotency} Potência de Sangue</span>}<span>+1 na Disciplina escolhida</span><span>+1 Especialização</span></div>{predatorRule.notes.map(note=><p key={note} className="package-note">{note}</p>)}<div className="predator-resolutions"><span>DECISÕES DO PACOTE</span>{predatorRule.resolutions.map(item=><label key={item.id} className={item.type==="ack"?"resolution-check":"resolution-field"}>{item.type==="ack"?<input type="checkbox" checked={character.data.predatorResolutions[item.id]==="confirmed"} onChange={event=>setData("predatorResolutions",{...character.data.predatorResolutions,[item.id]:event.target.checked?"confirmed":""})}/>:<input value={character.data.predatorResolutions[item.id]||""} onChange={event=>setData("predatorResolutions",{...character.data.predatorResolutions,[item.id]:event.target.value})} placeholder="Registre a escolha"/>}<span><strong>{item.label}<Status kind={item.required?"conditional":"optional"}/></strong><small>{item.description}</small></span></label>)}</div><button className="apply-package" disabled={!character.data.predatorDiscipline||!character.data.predatorSpecialty||character.data.predatorApplied===predatorRule.name} onClick={applyPredator}>{character.data.predatorApplied===predatorRule.name?<><Check size={16}/>Efeitos diretos aplicados</>:<>Aplicar efeitos diretos<ChevronRight size={16}/></>}</button></div>}
          <div className="form-grid"><Field label="Ressonância" status="conditional" value={character.data.resonance} onChange={v=>setData("resonance",v)}/><label className="field"><span>Fome atual<Status kind="optional"/></span><Dots label="Fome" max={5} value={character.data.hunger} onChange={v=>setData("hunger",v)}/></label></div>
        </Section>}
        {step===6&&<Section title="O que você possui — e o que o persegue?" subtitle="Vantagens e Defeitos preservam pontos, origem e observações."><MeritEditor title={`Vantagens — ${meritDots}/${meritTarget} pontos`} items={character.data.merits} onAdd={()=>addMerit("merits")} onUpdate={(i,p)=>updateMerit("merits",i,p)} onRemove={i=>removeMerit("merits",i)}/><MeritEditor title={`Defeitos — ${flawDots}/${flawTarget} pontos + Predador`} items={character.data.flawItems} onAdd={()=>addMerit("flawItems")} onUpdate={(i,p)=>updateMerit("flawItems",i,p)} onRemove={i=>removeMerit("flawItems",i)}/><RuleNote>“Tunnel Access” é uma vantagem de 1 ponto da loresheet The Labyrinth, Chicago by Night, p. 279. Se usada, selecione Chicago e registre “The Labyrinth”.</RuleNote></Section>}
        {step===7&&<Section title="O que ainda o torna humano?" subtitle="Cada Convicção deve estar ligada a um Pilar mortal."><div className="form-grid"><TextArea label="Convicções" status="required" value={character.data.convictions} onChange={v=>setData("convictions",v)} placeholder="Uma por linha"/><TextArea label="Pilares correspondentes" status="required" value={character.data.touchstones} onChange={v=>setData("touchstones",v)} placeholder="Na mesma ordem"/><Field wide label="Ambição" status="required" value={character.data.ambition} onChange={v=>setData("ambition",v)}/><Field wide label="Desejo" status="required" value={character.data.desire} onChange={v=>setData("desire",v)}/><label className="field wide"><span>Humanidade<Status kind="required"/></span><Dots label="Humanidade" max={10} min={1} value={character.data.humanity} onChange={v=>setData("humanity",v)}/></label><TextArea label="Princípios da Crônica" status="chronicle" value={character.data.chronicleTenets} onChange={v=>setData("chronicleTenets",v)} placeholder="Definidos pelo grupo/Narrador."/></div></Section>}
        {step===8&&<Section title="Quais regras valem nesta crônica?" subtitle="A regra-base continua visível; exceções ficam documentadas e nunca bloqueiam a ficha."><div className="chronicle-rules"><label className="chronicle-toggle"><input type="checkbox" checked={chronicle.customTargets} onChange={event=>setChronicleRule("customTargets",event.target.checked)}/><span><strong>Usar metas personalizadas de criação</strong><small>Substitui somente as metas numéricas abaixo.</small></span></label><div className="form-grid compact"><label className="field"><span>Pontos de Vantagens<Status kind="chronicle"/></span><input type="number" min={0} max={30} disabled={!chronicle.customTargets} value={chronicle.meritPoints} onChange={event=>setChronicleRule("meritPoints",Math.max(0,Number(event.target.value)))}/></label><label className="field"><span>Pontos de Defeitos<Status kind="chronicle"/></span><input type="number" min={0} max={30} disabled={!chronicle.customTargets} value={chronicle.flawPoints} onChange={event=>setChronicleRule("flawPoints",Math.max(0,Number(event.target.value)))}/></label><label className="field"><span>Pontos iniciais de Disciplinas<Status kind="chronicle"/></span><input type="number" min={0} max={15} disabled={!chronicle.customTargets} value={chronicle.disciplinePoints} onChange={event=>setChronicleRule("disciplinePoints",Math.max(0,Number(event.target.value)))}/></label></div><label className="chronicle-toggle"><input type="checkbox" checked={chronicle.generationOverride} onChange={event=>setChronicleRule("generationOverride",event.target.checked)}/><span><strong>A crônica substitui as faixas de Geração e Potência</strong><small>Desativa apenas esse aviso automático; os valores da ficha permanecem visíveis.</small></span></label><TextArea label="Notas e regras da crônica" status="chronicle" value={chronicle.notes} onChange={value=>setChronicleRule("notes",value)} placeholder="Exceções, fontes adicionais, limites e acordos do grupo."/><div className="chronicle-audit-callout"><CircleAlert size={18}/><div><strong>Permissões específicas</strong><p>Abra “Incoerências” e use “Permitir na crônica” para aprovar uma exceção individual sem esconder a diferença para a regra-base.</p></div><button onClick={()=>setAuditOpen(true)}>Abrir incoerências</button></div></div></Section>}
        {step===9&&<Section title="Revise antes da primeira noite" subtitle="Alertas orientam a criação; campos opcionais nunca bloqueiam a ficha."><div className="review-identity"><div className="review-seal">{(character.name||"?")[0]}</div><div><span>{character.concept||"CONCEITO NÃO DEFINIDO"}</span><h2>{character.name||"Sem nome"}</h2><p>{character.clan==="Personalizado"?character.data.customClan||"Linhagem personalizada":character.clan||"Sem Clã"} · {character.data.generation} Geração · Humanidade {character.data.humanity}</p></div><em className={`source ${selectedSource==="custom"?"custom":selectedSource==="chicago_by_night_v5"?"chicago":""}`}>{selectedSource==="custom"?"HOMEBREW":selectedSource==="chicago_by_night_v5"?"CHICAGO":"BÁSICO"}</em></div><div className="review-grid"><Review label="PREDADOR" value={character.data.predator||"Não escolhido"}/><Review label="VITALIDADE" value={String((character.data.attributes.Vigor||1)+3)}/><Review label="VONTADE" value={String((character.data.attributes.Autocontrole||1)+(character.data.attributes.Determinação||1))}/><Review label="POTÊNCIA" value={String(character.data.bloodPotency)}/></div><div className="form-grid"><Field label="XP total" value={character.data.xpTotal} onChange={v=>setData("xpTotal",v)}/><Field label="XP gasto" value={character.data.xpSpent} onChange={v=>setData("xpSpent",v)}/><TextArea label="Aparência" value={character.data.appearance} onChange={v=>setData("appearance",v)} placeholder="Descrição visual"/><TextArea label="Traços distintivos" value={character.data.distinguishingTraits} onChange={v=>setData("distinguishingTraits",v)} placeholder="Marcas, hábitos e sinais"/><TextArea label="História" value={character.data.history} onChange={v=>setData("history",v)} placeholder="Vida, Abraço e noites recentes"/><TextArea label="Notas livres e homebrews" value={character.data.notes} onChange={v=>setData("notes",v)} placeholder="Exceções e regras próprias."/></div><div className="final-checks">{validations.map(v=><div key={v.text} className={v.ok?"valid":"warning"}>{v.ok?<Check size={17}/>:<CircleAlert size={17}/>}<span>{v.text}</span><b>{v.ok?"Concluído":"Revisar"}</b></div>)}</div></Section>}
        <div className="editor-actions"><button disabled={step===0} className="secondary-action" onClick={()=>setStep(Math.max(0,step-1))}><ChevronLeft size={18}/>Voltar</button>{step<STEPS.length-1?<button className="primary-action" onClick={()=>setStep(step+1)}>Continuar<ChevronRight size={18}/></button>:<button className="primary-action" onClick={()=>save(character)}><Save size={17}/>Salvar ficha</button>}</div>
      </section>
      <aside className="right-rail"><div className="completion"><div><span>CRIAÇÃO</span><strong>{completed}/{validations.length}</strong></div><div className="completion-ring" style={{"--progress":`${completed/validations.length*360}deg`} as React.CSSProperties}><span>{Math.round(completed/validations.length*100)}%</span></div></div><div className="validation-list">{validations.map(v=><div key={v.text} className={v.ok?"passed":""}>{v.ok?<Check size={15}/>:<span/>}{v.text}</div>)}</div><button className="audit-button" onClick={()=>setAuditOpen(true)}><CircleAlert size={16}/><span><strong>Incoerências da ficha</strong><small>{auditIssues.filter(issue=>issue.kind==="warning").length?`${auditIssues.filter(issue=>issue.kind==="warning").length} aviso(s) para revisar`:"Nenhum aviso ativo"}</small></span></button><button className="source-panel source-button" onClick={()=>setSourcesOpen(true)}><span>FONTE DA ESCOLHA ATUAL</span><strong>{selectedSource==="custom"?"Conteúdo personalizado":selectedSource==="chicago_by_night_v5"?"Chicago by Night V5":"Livro Básico V5"}</strong><p>Abrir referências, páginas e status de normalização.</p></button><div className="freedom-note"><Sparkles size={17}/><div><strong>Sua crônica, suas regras</strong><p>Você pode continuar mesmo com alertas.</p></div></div></aside>
    </div>
    <nav className="mobile-action-bar" aria-label="Ações da criação">
      <button type="button" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}><ChevronLeft size={20}/><span>Voltar</span></button>
      <button type="button" onClick={()=>setMobileNav(true)}><Menu size={20}/><span>Etapas</span></button>
      <button type="button" onClick={()=>setAuditOpen(true)} className={auditIssues.some(issue=>issue.kind==="warning")?"has-warning":""}><CircleAlert size={20}/><span>Alertas</span>{auditIssues.filter(issue=>issue.kind==="warning").length>0&&<b>{auditIssues.filter(issue=>issue.kind==="warning").length}</b>}</button>
      {step<STEPS.length-1?<button type="button" className="mobile-primary" onClick={()=>setStep(step+1)}><ChevronRight size={20}/><span>Avançar</span></button>:<button type="button" className="mobile-primary" onClick={()=>save(character)}><Save size={20}/><span>Salvar</span></button>}
    </nav>
    <Sheet open={sourcesOpen} onOpenChange={setSourcesOpen}><SheetContent className="source-sheet sm:max-w-xl"><SheetHeader><SheetTitle>Fontes e regras</SheetTitle><SheetDescription>Referências usadas pelo criador. Resumos são rastreáveis; homebrew continua identificado.</SheetDescription></SheetHeader><div className="source-scroll"><Link className="open-library" href="/rules"><BookOpen size={17}/><span><strong>Abrir biblioteca completa</strong><small>Livros separados, índice por capítulos e busca</small></span><ChevronRight size={17}/></Link><SourceBook name="Livro Básico V5" code="BÁSICO" status="Base de criação" items={["Atributos: distribuição 1/3/4/1.","Habilidades: Pau pra toda obra 1×3, 8×2, 10×1; Equilibrado 3×3, 5×2, 7×1; Especialista 1×4, 3×3, 3×2, 3×1.","Disciplinas iniciais de Clã: uma em 2 e outra em 1.","Vantagens: 7 pontos. Defeitos: 2 pontos, além dos do Predador.","Humanidade inicial 7; de 1 a 3 Convicções, cada uma ligada a um Pilar."]}/><SourceBook name="Chicago by Night V5" code="CHICAGO" status="Suplemento ativo" items={["Lasombra: Dominação, Oblívio e Potência — livro p. 291 / PDF p. 292.","Compulsão Implacabilidade e Fraqueza — livro p. 292 / PDF p. 293.","Oblívio e poderes — livro pp. 293–297 / PDF pp. 294–298.","The Labyrinth: Tunnel Access é benefício de 1 ponto — livro p. 279 / PDF p. 280.","Tipos de coterie e demais loresheets permanecem contextuais até cada efeito ser normalizado."]}/><div className="source-legend"><h3>Como ler os rótulos</h3><p><Status kind="required"/> necessário na criação padrão.</p><p><Status kind="optional"/> pode ficar em branco.</p><p><Status kind="conditional"/> exigido por uma escolha.</p><p><Status kind="chronicle"/> definido pelo Narrador/grupo.</p></div></div></SheetContent></Sheet>
    <InconsistencySheet open={auditOpen} onOpenChange={setAuditOpen} issues={auditIssues} onToggleApproval={toggleApproval}/>
    {mobileNav&&<button className="nav-backdrop" onClick={()=>setMobileNav(false)} aria-label="Fechar navegação"><X/></button>}
  </main>
}

function Section({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="section"><div className="section-title"><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}
function RuleNote({children}:{children:React.ReactNode}){return <div className="rule-note"><BookOpen size={18}/><p><strong>Nota de regra</strong>{children}</p></div>}
function TraitGroup({title,names,values,onChange}:{title:string;names:string[];values:Values;onChange:(n:string,v:number)=>void}){return <div className="trait-group"><h3>{title}</h3>{names.map(name=><div className="trait" key={name}><span>{name}</span><Dots label={name} min={1} value={values[name]||1} onChange={v=>onChange(name,v)}/></div>)}</div>}
function ListHeading({title,copy,onAdd}:{title:string;copy:string;onAdd:()=>void}){return <div className="list-heading"><div><h3>{title}</h3><p>{copy}</p></div><button onClick={onAdd}><Plus size={15}/>Adicionar</button></div>}
function SourceSelect({value,onChange}:{value:string;onChange:(v:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}><option value="core_v5_ptbr">Livro Básico</option><option value="chicago_by_night_v5">Chicago</option><option value="custom">Homebrew</option></select>}
function MeritEditor({title,items,onAdd,onUpdate,onRemove}:{title:string;items:Merit[];onAdd:()=>void;onUpdate:(i:number,p:Partial<Merit>)=>void;onRemove:(i:number)=>void}){return <div className="merit-block"><ListHeading title={title} copy="Nome livre, pontuação e origem verificável." onAdd={onAdd}/>{items.length===0&&<p className="empty-row">Nenhum item adicionado.</p>}{items.map((m,i)=><div className="merit-row" key={i}><input value={m.name} onChange={e=>onUpdate(i,{name:e.target.value})} placeholder="Nome"/><Dots label={m.name||"Item"} value={m.dots} onChange={dots=>onUpdate(i,{dots})}/><SourceSelect value={m.source} onChange={source=>onUpdate(i,{source})}/><input value={m.notes} onChange={e=>onUpdate(i,{notes:e.target.value})} placeholder="Origem, loresheet ou observação"/><button onClick={()=>onRemove(i)}><Trash2 size={15}/></button></div>)}</div>}
function SourceBook({name,code,status,items}:{name:string;code:string;status:string;items:string[]}){return <article className="source-book"><div><span>{code}</span><em>{status}</em></div><h3>{name}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>}
function Review({label,value}:{label:string;value:string}){return <div className="review-card"><span>{label}</span><strong>{value}</strong></div>}
function PowerPicker({discipline,level,selected,onChange}:{discipline:string;level:number;selected:string[];onChange:(powers:string[])=>void}){
  const powers=POWER_CATALOG.filter(power=>power.discipline===discipline),catalogNames=new Set(powers.map(power=>power.name));
  const custom=selected.filter(name=>!catalogNames.has(name));
  return <div className="power-picker"><div className="power-picker-head"><span>PODERES CONHECIDOS</span><small>{selected.length}/{level} escolhas esperadas · avisos não bloqueiam</small></div>
    {powers.map(power=>{const active=selected.includes(power.name),aboveLevel=power.level>level;return <div className={`${active?"power-option active":"power-option"}${aboveLevel?" outside-rule":""}`} key={power.id}><button type="button" onClick={()=>onChange(active?selected.filter(name=>name!==power.name):[...selected,power.name])}><span>{active?<Check size={14}/>:null}</span><div><strong>{power.name}</strong><small>Nível {power.level}{power.amalgam?` · Amálgama: ${power.amalgam}`:""}{aboveLevel?" · acima do nível atual":""}</small></div></button><Link href={rulesUrl(power.source)}>Regra</Link></div>})}
    <label className="custom-power-list"><span>Poderes personalizados <Status kind="optional"/></span><textarea rows={2} value={custom.join("\n")} onChange={event=>onChange([...selected.filter(name=>catalogNames.has(name)),...event.target.value.split("\n").map(name=>name.trim()).filter(Boolean)])} placeholder="Um poder homebrew por linha"/></label>
  </div>
}
function predatorDescription(name:string){const map:Record<string,string>={Consensualista:"Busca consentimento para se alimentar",Fazendeiro:"Evita sangue humano e caça animais",Osíris:"Alimenta-se de seguidores e devotos",Sacoleiro:"Depende de sangue preservado",Sandman:"Caça vítimas adormecidas",Sanguessuga:"Alimenta-se de outros vampiros","Scene Queen":"Caça dentro de uma subcultura",Sereia:"Usa sedução para se aproximar",Trinchador:"Oculta a caça entre família e amigos","Vira-lata":"Caça por assalto e intimidação"};return map[name]}
