export type SourceRef={book:"core-v5"|"chicago-by-night-v5"|"camarilla-v5"|"anarch-v5"|"cultos-deuses-sangue-v5"|"companion-v5"|"sabbat-black-hand-v5"|"players-guide-v5"|"gehenna-war-v5"|"sigilos-de-sangue-v5";chapter:string;query:string;label:string};
export type PowerRule={id:string;name:string;discipline:string;level:number;cost:string;duration:string;pool?:string;amalgam?:string;source:SourceRef};
export type PredatorResolution={id:string;label:string;description:string;type:"ack"|"text"|"select";options?:string[];required:boolean};
export type PredatorRule={id:string;name:string;specialtyChoices:string[];disciplineChoices:string[];humanity:number;bloodPotency:number;notes:string[];resolutions:PredatorResolution[];source:SourceRef};
export type ChronicleRules={customTargets:boolean;meritPoints:number;flawPoints:number;disciplinePoints:number;generationOverride:boolean;notes:string;approvedIssueIds:string[]};
export const DEFAULT_CHRONICLE_RULES:ChronicleRules={customTargets:false,meritPoints:7,flawPoints:2,disciplinePoints:3,generationOverride:false,notes:"",approvedIssueIds:[]};

const chicagoLasombra:SourceRef={book:"chicago-by-night-v5",chapter:"capitulos-chapter-six-lasombra",query:"Oblivion",label:"Chicago by Night, livro pp. 293–297"};
export const OBLIVION_POWERS:PowerRule[]=[
  {id:"shadow-cloak",name:"Shadow Cloak",discipline:"Oblívio",level:1,cost:"Gratuito",duration:"Passivo",source:chicagoLasombra},
  {id:"oblivions-sight",name:"Oblivion’s Sight",discipline:"Oblívio",level:1,cost:"Gratuito",duration:"Uma cena",source:chicagoLasombra},
  {id:"shadow-cast",name:"Shadow Cast",discipline:"Oblívio",level:2,cost:"Um Teste de Despertar",duration:"Uma cena",source:chicagoLasombra},
  {id:"arms-of-ahriman",name:"Arms of Ahriman",discipline:"Oblívio",level:2,cost:"Um Teste de Despertar",duration:"Uma cena ou até terminar/ser destruído",pool:"Raciocínio + Oblívio",amalgam:"Potência 2",source:chicagoLasombra},
  {id:"shadow-perspective",name:"Shadow Perspective",discipline:"Oblívio",level:3,cost:"Um Teste de Despertar",duration:"Até uma cena",source:chicagoLasombra},
  {id:"touch-of-oblivion",name:"Touch of Oblivion",discipline:"Oblívio",level:3,cost:"Um Teste de Despertar",duration:"Um turno",source:chicagoLasombra},
  {id:"stygian-shroud",name:"Stygian Shroud",discipline:"Oblívio",level:4,cost:"Um Teste de Despertar",duration:"Uma cena",source:chicagoLasombra},
  {id:"shadow-step",name:"Shadow Step",discipline:"Oblívio",level:5,cost:"Um Teste de Despertar",duration:"Um turno",source:chicagoLasombra},
  {id:"tenebrous-avatar",name:"Tenebrous Avatar",discipline:"Oblívio",level:5,cost:"Dois Testes de Despertar",duration:"Uma cena ou até terminar",source:chicagoLasombra},
];

const predatorSource=(query:string):SourceRef=>({book:"core-v5",chapter:"regras-e-criacao-tipos-de-predador",query,label:"Livro Básico V5, pp. 175–178"});
const playerPredatorSource=(query:string):SourceRef=>({book:"players-guide-v5",chapter:"players-guide-v5-predator-types",query,label:"Player’s Guide V5, PDF pp. 109–111"});
export const PREDATOR_RULES:PredatorRule[]=[
  {id:"consensualista",name:"Consensualista",specialtyChoices:["Medicina","Persuasão"],disciplineChoices:["Auspícios","Fortitude"],humanity:1,bloodPotency:0,notes:["Defeitos ligados à Máscara e à exclusão de presas sem consentimento devem ser escolhidos."],resolutions:[{id:"mask-flaw",label:"Defeito ligado à Máscara",description:"Registre o Defeito indicado pelo tipo.",type:"text",required:true},{id:"prey-exclusion",label:"Exclusão de Presa",description:"Confirme a exclusão de presas sem consentimento.",type:"ack",required:true}],source:predatorSource("Consensualista")},
  {id:"fazendeiro",name:"Fazendeiro",specialtyChoices:["Empatia com Animais","Sobrevivência"],disciplineChoices:["Animalismo","Proteanismo"],humanity:1,bloodPotency:0,notes:["Recebe o Defeito de alimentação Fazendeiro; há restrições para Ventrue e Potência de Sangue elevada."],resolutions:[{id:"farmer-flaw",label:"Defeito Fazendeiro",description:"Confirme o Defeito de alimentação recebido.",type:"ack",required:true},{id:"restriction",label:"Restrição conferida",description:"Confirme com o Narrador as restrições para Ventrue e Potência de Sangue elevada.",type:"ack",required:true}],source:predatorSource("Fazendeiro")},
  {id:"osiris",name:"Osíris",specialtyChoices:["Ocultismo","Performance"],disciplineChoices:["Feitiçaria de Sangue","Presença"],humanity:0,bloodPotency:0,notes:["Fama/Rebanho e Defeitos dependem das escolhas do personagem."],resolutions:[{id:"fame-herd",label:"Distribuição entre Fama e Rebanho",description:"Registre como os pontos indicados no livro foram distribuídos.",type:"text",required:true},{id:"osiris-flaws",label:"Defeitos escolhidos",description:"Registre Inimigos/Defeitos Míticos escolhidos.",type:"text",required:true}],source:predatorSource("Osíris")},
  {id:"sacoleiro",name:"Sacoleiro",specialtyChoices:["Ladroagem","Manha"],disciplineChoices:["Feitiçaria de Sangue","Ofuscação"],humanity:0,bloodPotency:0,notes:["Concede Esôfago de Ferro e um Inimigo; os pontos devem ser confirmados no livro."],resolutions:[{id:"iron-gullet",label:"Esôfago de Ferro",description:"Confirme a Qualidade de alimentação recebida.",type:"ack",required:true},{id:"enemy",label:"Inimigo",description:"Identifique o Inimigo ligado à origem ou ao acesso ao sangue.",type:"text",required:true}],source:predatorSource("Sacoleiro")},
  {id:"sandman",name:"Sandman",specialtyChoices:["Medicina","Furtividade"],disciplineChoices:["Auspícios","Ofuscação"],humanity:0,bloodPotency:0,notes:["Concede Recursos; a quantidade deve ser confirmada no livro."],resolutions:[{id:"resources",label:"Recursos recebidos",description:"Registre os Recursos indicados pelo tipo após conferir a pontuação na fonte.",type:"text",required:true}],source:predatorSource("Sandman")},
  {id:"sanguessuga",name:"Sanguessuga",specialtyChoices:["Briga","Furtividade"],disciplineChoices:["Celeridade","Proteanismo"],humanity:-1,bloodPotency:1,notes:["Segredo Sombrio/segregação e Exclusão de Presa exigem escolha."],resolutions:[{id:"dark-secret",label:"Segredo Sombrio ou segregação",description:"Registre a opção recebida pelo personagem.",type:"text",required:true},{id:"mortals-excluded",label:"Exclusão de Presa: mortais",description:"Confirme a exclusão de mortais.",type:"ack",required:true}],source:predatorSource("Sanguessuga")},
  {id:"scene-queen",name:"Scene Queen",specialtyChoices:["Etiqueta","Liderança","Manha"],disciplineChoices:["Dominação","Potência"],humanity:0,bloodPotency:0,notes:["Fama, Contatos e Defeito são ligados à subcultura escolhida."],resolutions:[{id:"scene",label:"Subcultura",description:"Defina a cena social usada para caçar.",type:"text",required:true},{id:"fame-contacts",label:"Fama e Contatos",description:"Registre os benefícios ligados à subcultura.",type:"text",required:true},{id:"scene-flaw",label:"Defeito da cena",description:"Registre o Defeito ou Exclusão de Presa correspondente.",type:"text",required:true}],source:predatorSource("Scene Queen")},
  {id:"sereia",name:"Sereia",specialtyChoices:["Persuasão","Subterfúgio"],disciplineChoices:["Fortitude","Presença"],humanity:0,bloodPotency:0,notes:["Concede Belo e um Inimigo ligado a amante/parceiro."],resolutions:[{id:"beautiful",label:"Belo",description:"Confirme a Qualidade Visual recebida.",type:"ack",required:true},{id:"lover-enemy",label:"Inimigo",description:"Identifique o amante ou parceiro desprezado/ciumento.",type:"text",required:true}],source:predatorSource("Sereia")},
  {id:"trinchador",name:"Trinchador",specialtyChoices:["Persuasão","Subterfúgio"],disciplineChoices:["Dominação","Animalismo"],humanity:0,bloodPotency:0,notes:["Família no Mapa de Relacionamentos, Segredo Sombrio e Rebanho exigem registro."],resolutions:[{id:"family",label:"Família ou grupo",description:"Registre quem compõe a família usada na caça.",type:"text",required:true},{id:"cleaver-secret",label:"Segredo Sombrio: Trinchador",description:"Confirme o Segredo Sombrio recebido.",type:"ack",required:true},{id:"family-herd",label:"Rebanho",description:"Registre o Rebanho relacionado à família ou grupo.",type:"text",required:true}],source:predatorSource("Trinchador")},
  {id:"vira-lata",name:"Vira-lata",specialtyChoices:["Intimidação","Briga"],disciplineChoices:["Celeridade","Potência"],humanity:-1,bloodPotency:0,notes:["Concede Contatos criminosos; a quantidade deve ser confirmada no livro."],resolutions:[{id:"criminal-contacts",label:"Contatos criminosos",description:"Identifique os contatos recebidos e registre a pontuação após conferir a fonte.",type:"text",required:true}],source:predatorSource("Vira-lata")},
  {id:"extortionist",name:"Extortionist",specialtyChoices:["Intimidação","Ladroagem"],disciplineChoices:["Dominação","Potência"],humanity:0,bloodPotency:0,notes:["Distribua 3 pontos entre Contatos e Recursos; receba Inimigo 2 (polícia ou vítima)."],resolutions:[{id:"contacts-resources",label:"Contatos e Recursos",description:"Registre a distribuição dos 3 pontos.",type:"text",required:true},{id:"enemy",label:"Inimigo 2",description:"Identifique a polícia ou a vítima que busca vingança.",type:"text",required:true}],source:playerPredatorSource("Extortionist")},
  {id:"graverobber",name:"Graverobber",specialtyChoices:["Ocultismo","Medicina"],disciplineChoices:["Fortitude","Oblívio"],humanity:0,bloodPotency:0,notes:["Recebe Esôfago de Ferro 3, Refúgio 1 e Defeito de Rebanho 2: Predador Óbvio."],resolutions:[{id:"iron-gullet",label:"Esôfago de Ferro 3",description:"Registre a Qualidade de alimentação.",type:"ack",required:true},{id:"haven-herd",label:"Refúgio e Defeito de Rebanho",description:"Confirme Refúgio 1 e Predador Óbvio 2.",type:"ack",required:true}],source:playerPredatorSource("Graverobber")},
  {id:"grim-reaper",name:"Grim Reaper",specialtyChoices:["Percepção","Ladroagem"],disciplineChoices:["Auspícios","Oblívio"],humanity:1,bloodPotency:0,notes:["Recebe 1 ponto em Aliados ou Influência na comunidade médica e Exclusão de Presa 1: mortais saudáveis."],resolutions:[{id:"medical-background",label:"Aliados ou Influência",description:"Escolha o Antecedente médico que recebe 1 ponto.",type:"text",required:true},{id:"prey-exclusion",label:"Exclusão de Presa",description:"Confirme a exclusão de mortais saudáveis.",type:"ack",required:true}],source:playerPredatorSource("Grim Reaper")},
  {id:"montero",name:"Montero",specialtyChoices:["Liderança","Furtividade"],disciplineChoices:["Dominação","Ofuscação"],humanity:-1,bloodPotency:0,notes:["Recebe Lacaios 2 e perde 1 ponto de Humanidade."],resolutions:[{id:"retainers",label:"Lacaios 2",description:"Identifique a equipe que conduz as presas.",type:"text",required:true}],source:playerPredatorSource("Montero")},
  {id:"pursuer",name:"Pursuer",specialtyChoices:["Investigação","Furtividade"],disciplineChoices:["Animalismo","Auspícios"],humanity:-1,bloodPotency:0,notes:["Recebe Faro para Sangue 1 e Contatos 1 no território de caça; perde 1 ponto de Humanidade."],resolutions:[{id:"bloodhound",label:"Faro para Sangue 1",description:"Confirme a Qualidade recebida.",type:"ack",required:true},{id:"contacts",label:"Contatos 1",description:"Identifique o contato no território de caça.",type:"text",required:true}],source:playerPredatorSource("Pursuer")},
  {id:"trapdoor",name:"Trapdoor",specialtyChoices:["Persuasão","Furtividade"],disciplineChoices:["Proteanismo","Ofuscação"],humanity:0,bloodPotency:0,notes:["Recebe Refúgio 1 e mais 1 ponto em Lacaios, Rebanho ou Refúgio; escolha Defeito de Refúgio 1: Assustador ou Assombrado."],resolutions:[{id:"second-background",label:"Lacaios, Rebanho ou Refúgio",description:"Registre o segundo ponto de Antecedente.",type:"text",required:true},{id:"haven-flaw",label:"Defeito de Refúgio 1",description:"Escolha Assustador ou Assombrado.",type:"text",required:true}],source:playerPredatorSource("Trapdoor")},
];

const coreDiscipline=(discipline:string,pages:string):SourceRef=>({book:"core-v5",chapter:"regras-e-criacao-disciplinas",query:discipline,label:`Livro Básico V5, pp. ${pages}`});
const catalog=(discipline:string,pages:string,entries:Array<[string,string,number,string?]>):PowerRule[]=>entries.map(([id,name,level,amalgam])=>({id,name,discipline,level,cost:"Consultar regra",duration:"Consultar regra",amalgam,source:{...coreDiscipline(discipline,pages),query:name}}));
export const CORE_POWER_CATALOG:PowerRule[]=[
  ...catalog("Animalismo","245–248",[["bond-famulus","Enlaçar Fâmulo",1],["sense-the-beast","Sentir a Besta",1],["feral-whispers","Sussurros Selvagens",2],["unliving-hive","Enxame Não Vivo",2,"Ofuscação 2"],["quell-the-beast","Subjugar a Besta",3],["animal-succulence","Suculência Animal",3],["subsume-spirit","Comunhão de Espíritos",4],["animal-dominion","Controle Animal",5],["drawing-out-beast","Expulsar a Besta",5]]),
  ...catalog("Auspícios","248–252",[["heightened-senses","Sentidos Aguçados",1],["sense-unseen","Sentir o Invisível",1],["premonition","Premonição",2],["scry-soul","Perscrutar a Alma",3],["share-senses","Compartilhar os Sentidos",3],["spirits-touch","Toque do Espírito",4],["clairvoyance","Clarividência",5],["possession","Possessão",5,"Dominação 3"],["telepathy","Telepatia",5]]),
  ...catalog("Celeridade","252–254",[["cats-grace","Graça Felina",1],["rapid-reflexes","Reflexos Rápidos",1],["fleetness","Rapidez",2],["blink","Piscar",3],["traversal","Travessia",3],["draught-elegance","Elegância Direto da Fonte",4],["unerring-aim","Mira Infalível",4,"Auspícios 2"],["lightning-strike","Golpe Relâmpago",5],["split-second","Fração de Segundo",5]]),
  ...catalog("Dominação","254–257",[["cloud-memory","Nublar Memória",1],["compel","Compelir",1],["mesmerize","Mesmerismo",2],["dementation","Dementação",2,"Ofuscação 2"],["forgetful-mind","Mente Esquecida",3],["submerged-directive","Diretriz Submersa",3],["rationalize","Racionalizar",4],["mass-manipulation","Manipulação em Massa",5],["terminal-decree","Decreto Terminal",5]]),
  ...catalog("Fortitude","258–260",[["resilience","Resiliência",1],["unswayable-mind","Mente Inescrutável",1],["toughness","Tenacidade",2],["enduring-beasts","Feras Tenazes",2,"Animalismo 1"],["defy-bane","Desafio à Perdição",3],["fortify-inner-facade","Fortificar a Fachada Interior",3],["draught-endurance","Resistência Direto da Fonte",4],["flesh-marble","Pele de Mármore",5],["prowess-pain","Poder Vindo da Dor",5]]),
  ...catalog("Ofuscação","260–263",[["cloak-shadows","Manto de Sombras",1],["silence-death","Silêncio da Morte",1],["unseen-passage","Passagem Invisível",2],["ghost-machine","Fantasma na Máquina",3],["mask-thousand","Máscara de Mil Faces",3],["vanish","Desaparecer",4],["conceal","Ocultar",4],["impostors-guise","Disfarce do Impostor",5],["cloak-gathering","Ocultar o Grupo",5]]),
  ...catalog("Potência","263–265",[["lethal-body","Corpo Letal",1],["soaring-leap","Salto Vertiginoso",1],["prowess","Poderio",2],["brutal-feed","Alimentação Brutal",3],["spark-rage","Centelha de Fúria",3],["uncanny-grip","Pegada Sobrenatural",3],["draught-might","Potência Direto da Fonte",4],["earthshock","Terremoto",5],["fist-caine","Punho de Caim",5]]),
  ...catalog("Presença","266–268",[["awe","Fascínio",1],["daunt","Amedrontar",1],["lingering-kiss","Beijo Persistente",2],["dread-gaze","Olhar Aterrorizante",3],["entrancement","Transe",3],["irresistible-voice","Voz Irresistível",4,"Dominação 1"],["summon","Convocar",4],["majesty","Majestade",5],["star-magnetism","Magnetismo de Estrela",5]]),
  ...catalog("Proteanismo","269–271",[["eyes-beast","Olhos da Besta",1],["weight-feather","Peso Pena",1],["feral-weapons","Armas Ferais",2],["earth-meld","Fusão com a Terra",3],["shapechange","Mudança de Forma",3],["metamorphosis","Metamorfose",4],["mist-form","Forma de Névoa",5],["unfettered-heart","Coração Vagante",5]]),
  ...catalog("Feitiçaria de Sangue","272–274",[["taste-blood","Um Gosto por Sangue",1],["corrosive-vitae","Vitae Corrosivo",1],["extinguish-vitae","Extinguir Vitae",2],["scorpions-touch","Picada de Escorpião",3],["blood-potency","Sangue Potente",3],["theft-vitae","Roubo de Vitae",4],["baals-caress","Carícia de Baal",5],["cauldron-blood","Caldeirão de Sangue",5]]),
];
const playerPowerSource=(name:string):SourceRef=>({book:"players-guide-v5",chapter:"players-guide-v5-discipline-powers",query:name,label:"Player’s Guide V5, Disciplinas, PDF pp. 71–80"});
const playerPowers:Array<[string,string,string,number,string?]>=[
  ["animal-messenger","Animal Messenger","Animalismo",2,"Auspícios 1"],
  ["messengers-command","Messenger’s Command","Animalismo",3,"Dominação 1"],
  ["plague-of-beasts","Plague of Beasts","Animalismo",3],
  ["sway-the-flock","Sway the Flock","Animalismo",4],
  ["coax-bestial-temper","Coax the Bestial Temper","Animalismo",5],
  ["panacea","Panacea","Auspícios",2,"Fortitude 1"],
  ["reveal-temperament","Reveal Temperament","Auspícios",2],
  ["fatal-flaw","Fatal Flaw","Auspícios",3,"Oblívio 1"],
  ["unburdening-bestial-soul","Unburdening the Bestial Soul","Auspícios",5,"Dominação 3"],
  ["rush-job","Rush Job","Celeridade",2],
  ["weaving","Weaving","Celeridade",3],
  ["blurred-momentum","Blurred Momentum","Celeridade",4],
  ["earths-perseverance","Earth’s Perseverance","Fortitude",2],
  ["invigorating-vitae","Invigorating Vitae","Fortitude",2,"Auspícios 1"],
  ["valeren","Valeren","Fortitude",3,"Auspícios 1"],
  ["gorgons-scales","Gorgon’s Scales","Fortitude",4],
  ["chimerstry","Chimerstry","Ofuscação",2,"Presença 1"],
  ["fata-morgana","Fata Morgana","Ofuscação",3,"Presença 2"],
  ["mental-maze","Mental Maze","Ofuscação",3,"Dominação 1"],
];
export const PLAYER_POWER_CATALOG:PowerRule[]=playerPowers.map(([id,name,discipline,level,amalgam])=>({id,name,discipline,level,cost:"Consultar regra",duration:"Consultar regra",amalgam,source:playerPowerSource(name)}));
export const POWER_CATALOG=[...CORE_POWER_CATALOG,...OBLIVION_POWERS,...PLAYER_POWER_CATALOG];

export const SKILL_PRESETS:Record<string,Record<number,number>>={
  "Pau pra toda obra":{3:1,2:8,1:10},"Equilibrado":{3:3,2:5,1:7},"Especialista":{4:1,3:3,2:3,1:3},
};
export const AGE_RULES:Record<string,{generations:string[];bloodPotency:number;note:string}>={
  "Criança da Noite":{generations:["12ª","13ª"],bloodPotency:1,note:"Sangues-Ralos podem estar entre 14ª e 16ª Geração, com Potência de Sangue 0."},
  "Neófito":{generations:["12ª","13ª"],bloodPotency:1,note:"Faixa padrão resumida do Livro Básico."},
  "Ancilla":{generations:["10ª","11ª"],bloodPotency:2,note:"Faixa padrão resumida do Livro Básico."},
};

export function rulesUrl(source:SourceRef){return `/rules?book=${source.book}&chapter=${source.chapter}&q=${encodeURIComponent(source.query)}`}
