import assert from "node:assert/strict";
import fs from "node:fs";
import ts from "typescript";

const source = fs.readFileSync(new URL("../app/play/dice.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const loaded = { exports: {} };
new Function("module", "exports", compiled)(loaded, loaded.exports);
const { evaluateTest, rollPool, rerollDice, resolveRouseCheck } = loaded.exports;
const die = (value, hunger = false) => ({ value, hunger });
assert.equal(evaluateTest([die(10), die(10)], 4).successes, 4);
assert.equal(evaluateTest([die(10), die(10), die(10), die(10)], 8).successes, 8);
assert.equal(evaluateTest([die(10), die(10), die(10)], 5).successes, 5);
assert.equal(evaluateTest([die(10), die(10)], 4).type, "critical");
assert.equal(evaluateTest([die(10, true), die(10)], 4).type, "messy");
assert.equal(evaluateTest([die(10, true), die(10)], 5).type, "failure");
assert.equal(evaluateTest([die(10, true), die(6)], 2).type, "success");
assert.equal(evaluateTest([die(1, true), die(6)], 1).type, "success");
assert.equal(evaluateTest([die(1, true), die(6)], 2).type, "bestial");
assert.equal(evaluateTest([die(1), die(5)], 1).type, "failure");
assert.equal(rollPool(2, 5, () => 0).filter(item => item.hunger).length, 2);
assert.equal(rollPool(8, 5, () => .99).filter(item => item.hunger).length, 5);
assert.equal(rollPool(8, 0).filter(item => item.hunger).length, 0);
const original = [die(10, true), die(10), die(1), die(5), die(6)];
assert.equal(rerollDice(original, [0]), null, "Fome não pode ser rerrolada");
assert.equal(rerollDice(original, [1, 2, 3, 4]), null, "Máximo de três dados");
assert.equal(rerollDice(original, []), null);
const rerolled = rerollDice(original, [1], () => .5);
assert.equal(rerolled[1].previousValue, 10);
assert.equal(rerolled[1].value, 6);
assert.deepEqual(rerolled[0], original[0]);
assert.equal(original[1].value, 10, "Histórico anterior preservado");
assert.equal(evaluateTest(rerolled, 3).type, "success", "Rerrolar 10 comum pode desfazer crítico bestial");
assert.equal(resolveRouseCheck(2, 5).hunger, 3);
assert.equal(resolveRouseCheck(2, 6).hunger, 2);
assert.equal(resolveRouseCheck(5, 1).hunger, 5);
assert.equal(resolveRouseCheck(0, 1).successes, 0);
console.log("Dados V5 conferidos: sucessos, pares críticos, Fome, falha bestial e rerrolagem de Vontade.");
