create table public.characters (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null default 'Sem nome' check (char_length(name) <= 120),
  concept text not null default '' check (char_length(concept) <= 240),
  clan text not null default '' check (char_length(clan) <= 80),
  sourcebook text not null default 'core_v5_ptbr' check (char_length(sourcebook) <= 80),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index characters_user_updated_idx on public.characters (user_id, updated_at desc);
alter table public.characters enable row level security;
create policy "Users can read their own characters" on public.characters for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can create their own characters" on public.characters for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own characters" on public.characters for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users can delete their own characters" on public.characters for delete to authenticated using ((select auth.uid()) = user_id);
grant select, insert, update, delete on table public.characters to authenticated;
grant usage, select on sequence public.characters_id_seq to authenticated;
